/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActivityCreateNestedManyWithoutUserRolesInput } from "./ActivityCreateNestedManyWithoutUserRolesInput";
import { ValidateNested, IsOptional, IsBoolean, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { CategoryCreateNestedManyWithoutUserRolesInput } from "./CategoryCreateNestedManyWithoutUserRolesInput";
import { FundraiserCreateNestedManyWithoutUserRolesInput } from "./FundraiserCreateNestedManyWithoutUserRolesInput";
import { FundraisersCustomerCreateNestedManyWithoutUserRolesInput } from "./FundraisersCustomerCreateNestedManyWithoutUserRolesInput";
import { InboxCreateNestedManyWithoutUserRolesInput } from "./InboxCreateNestedManyWithoutUserRolesInput";
import { MessageCreateNestedManyWithoutUserRolesInput } from "./MessageCreateNestedManyWithoutUserRolesInput";
import { NotificationCreateNestedManyWithoutUserRolesInput } from "./NotificationCreateNestedManyWithoutUserRolesInput";
import { OrderCreateNestedManyWithoutUserRolesInput } from "./OrderCreateNestedManyWithoutUserRolesInput";
import { PostcodeCreateNestedManyWithoutUserRolesInput } from "./PostcodeCreateNestedManyWithoutUserRolesInput";
import { ProductCreateNestedManyWithoutUserRolesInput } from "./ProductCreateNestedManyWithoutUserRolesInput";
import { EnumUserRoleRoles } from "./EnumUserRoleRoles";
import { SubscriptionCreateNestedManyWithoutUserRolesInput } from "./SubscriptionCreateNestedManyWithoutUserRolesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class UserRoleCreateInput {
  @ApiProperty({
    required: false,
    type: () => ActivityCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => ActivityCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => ActivityCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  activities?: ActivityCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => CategoryCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => CategoryCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => CategoryCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  categories?: CategoryCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  emailNotification!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  enabled!: boolean;

  @ApiProperty({
    required: false,
    type: () => FundraiserCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => FundraiserCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => FundraiserCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  fundraisers?: FundraiserCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => FundraiserCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => FundraiserCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => FundraiserCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  fundraisersFundraisersSupplierUuidToUserRoles?: FundraiserCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => FundraisersCustomerCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => FundraisersCustomerCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => FundraisersCustomerCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  fundraiserscustomers?: FundraisersCustomerCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => InboxCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => InboxCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => InboxCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  inboxReceiver?: InboxCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => InboxCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => InboxCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => InboxCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  inboxSender?: InboxCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  orders?: OrderCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => PostcodeCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => PostcodeCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => PostcodeCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  postcodes?: PostcodeCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  products?: ProductCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    enum: EnumUserRoleRoles,
  })
  @IsEnum(EnumUserRoleRoles)
  @IsOptional()
  @Field(() => EnumUserRoleRoles, {
    nullable: true,
  })
  roles?:
    | "ADMIN"
    | "MANAGER"
    | "SUPPLIER"
    | "REFERRER"
    | "CUSTOMER"
    | "SUPERADMIN"
    | "SUPPLIERADMIN"
    | null;

  @ApiProperty({
    required: false,
    type: () => SubscriptionCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => SubscriptionCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => OrderCreateNestedManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => OrderCreateNestedManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => OrderCreateNestedManyWithoutUserRolesInput, {
    nullable: true,
  })
  supplier?: OrderCreateNestedManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  users?: UserWhereUniqueInput | null;
}

export { UserRoleCreateInput as UserRoleCreateInput };
