/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserRoleService } from "../userRole.service";
import { UserRoleCreateInput } from "./UserRoleCreateInput";
import { UserRole } from "./UserRole";
import { UserRoleFindManyArgs } from "./UserRoleFindManyArgs";
import { UserRoleWhereUniqueInput } from "./UserRoleWhereUniqueInput";
import { UserRoleUpdateInput } from "./UserRoleUpdateInput";
import { ActivityFindManyArgs } from "../../activity/base/ActivityFindManyArgs";
import { Activity } from "../../activity/base/Activity";
import { ActivityWhereUniqueInput } from "../../activity/base/ActivityWhereUniqueInput";
import { CategoryFindManyArgs } from "../../category/base/CategoryFindManyArgs";
import { Category } from "../../category/base/Category";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { FundraiserFindManyArgs } from "../../fundraiser/base/FundraiserFindManyArgs";
import { Fundraiser } from "../../fundraiser/base/Fundraiser";
import { FundraiserWhereUniqueInput } from "../../fundraiser/base/FundraiserWhereUniqueInput";
import { FundraisersCustomerFindManyArgs } from "../../fundraisersCustomer/base/FundraisersCustomerFindManyArgs";
import { FundraisersCustomer } from "../../fundraisersCustomer/base/FundraisersCustomer";
import { FundraisersCustomerWhereUniqueInput } from "../../fundraisersCustomer/base/FundraisersCustomerWhereUniqueInput";
import { InboxFindManyArgs } from "../../inbox/base/InboxFindManyArgs";
import { Inbox } from "../../inbox/base/Inbox";
import { InboxWhereUniqueInput } from "../../inbox/base/InboxWhereUniqueInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";
import { NotificationFindManyArgs } from "../../notification/base/NotificationFindManyArgs";
import { Notification } from "../../notification/base/Notification";
import { NotificationWhereUniqueInput } from "../../notification/base/NotificationWhereUniqueInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
import { PostcodeFindManyArgs } from "../../postcode/base/PostcodeFindManyArgs";
import { Postcode } from "../../postcode/base/Postcode";
import { PostcodeWhereUniqueInput } from "../../postcode/base/PostcodeWhereUniqueInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { SubscriptionWhereUniqueInput } from "../../subscription/base/SubscriptionWhereUniqueInput";

export class UserRoleControllerBase {
  constructor(protected readonly service: UserRoleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserRole })
  async createUserRole(
    @common.Body() data: UserRoleCreateInput
  ): Promise<UserRole> {
    return await this.service.createUserRole({
      data: {
        ...data,

        users: data.users
          ? {
              connect: data.users,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        emailNotification: true,
        enabled: true,
        id: true,
        roles: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserRole] })
  @ApiNestedQuery(UserRoleFindManyArgs)
  async userRoles(@common.Req() request: Request): Promise<UserRole[]> {
    const args = plainToClass(UserRoleFindManyArgs, request.query);
    return this.service.userRoles({
      ...args,
      select: {
        createdAt: true,
        emailNotification: true,
        enabled: true,
        id: true,
        roles: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserRole })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userRole(
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<UserRole | null> {
    const result = await this.service.userRole({
      where: params,
      select: {
        createdAt: true,
        emailNotification: true,
        enabled: true,
        id: true,
        roles: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserRole })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserRole(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() data: UserRoleUpdateInput
  ): Promise<UserRole | null> {
    try {
      return await this.service.updateUserRole({
        where: params,
        data: {
          ...data,

          users: data.users
            ? {
                connect: data.users,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          emailNotification: true,
          enabled: true,
          id: true,
          roles: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserRole })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserRole(
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<UserRole | null> {
    try {
      return await this.service.deleteUserRole({
        where: params,
        select: {
          createdAt: true,
          emailNotification: true,
          enabled: true,
          id: true,
          roles: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/activities")
  @ApiNestedQuery(ActivityFindManyArgs)
  async findActivities(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Activity[]> {
    const query = plainToClass(ActivityFindManyArgs, request.query);
    const results = await this.service.findActivities(params.id, {
      ...query,
      select: {
        activityStatus: true,
        assigned: true,
        createdAt: true,
        dueDate: true,
        email: true,
        id: true,
        image: true,
        link: true,
        linkDrawer: true,
        linkName: true,
        linkUuid: true,
        text: true,
        updatedAt: true,
        userName: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/activities")
  async connectActivities(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/activities")
  async updateActivities(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/activities")
  async disconnectActivities(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: ActivityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      activities: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/categories")
  @ApiNestedQuery(CategoryFindManyArgs)
  async findCategories(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Category[]> {
    const query = plainToClass(CategoryFindManyArgs, request.query);
    const results = await this.service.findCategories(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        quickStarter: true,
        title: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/categories")
  async connectCategories(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: CategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categories: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/categories")
  async updateCategories(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: CategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categories: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/categories")
  async disconnectCategories(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: CategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categories: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraisers")
  @ApiNestedQuery(FundraiserFindManyArgs)
  async findFundraisers(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Fundraiser[]> {
    const query = plainToClass(FundraiserFindManyArgs, request.query);
    const results = await this.service.findFundraisers(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        endDate: true,

        fundraisersimages: {
          select: {
            id: true,
          },
        },

        fundraisersstatus: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        link: true,
        postcode: true,
        startDate: true,
        subscribed: true,
        suburb: true,
        target: true,
        title: true,
        topic: true,

        topics: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        userRolesFundraisersSupplierUuidToUserRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisers")
  async connectFundraisers(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisers: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisers")
  async updateFundraisers(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisers: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisers")
  async disconnectFundraisers(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisers: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraisersFundraisersSupplierUuidToUserRoles")
  @ApiNestedQuery(FundraiserFindManyArgs)
  async findFundraisersFundraisersSupplierUuidToUserRoles(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Fundraiser[]> {
    const query = plainToClass(FundraiserFindManyArgs, request.query);
    const results =
      await this.service.findFundraisersFundraisersSupplierUuidToUserRoles(
        params.id,
        {
          ...query,
          select: {
            createdAt: true,
            description: true,
            endDate: true,

            fundraisersimages: {
              select: {
                id: true,
              },
            },

            fundraisersstatus: {
              select: {
                id: true,
              },
            },

            id: true,
            image: true,
            link: true,
            postcode: true,
            startDate: true,
            subscribed: true,
            suburb: true,
            target: true,
            title: true,
            topic: true,

            topics: {
              select: {
                id: true,
              },
            },

            updatedAt: true,

            userRoles: {
              select: {
                id: true,
              },
            },

            userRolesFundraisersSupplierUuidToUserRoles: {
              select: {
                id: true,
              },
            },
          },
        }
      );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisersFundraisersSupplierUuidToUserRoles")
  async connectFundraisersFundraisersSupplierUuidToUserRoles(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersFundraisersSupplierUuidToUserRoles: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisersFundraisersSupplierUuidToUserRoles")
  async updateFundraisersFundraisersSupplierUuidToUserRoles(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersFundraisersSupplierUuidToUserRoles: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisersFundraisersSupplierUuidToUserRoles")
  async disconnectFundraisersFundraisersSupplierUuidToUserRoles(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersFundraisersSupplierUuidToUserRoles: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraiserscustomers")
  @ApiNestedQuery(FundraisersCustomerFindManyArgs)
  async findFundraiserscustomers(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<FundraisersCustomer[]> {
    const query = plainToClass(FundraisersCustomerFindManyArgs, request.query);
    const results = await this.service.findFundraiserscustomers(params.id, {
      ...query,
      select: {
        createdAt: true,

        fundraiser: {
          select: {
            id: true,
          },
        },

        fundraisersStatus: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraiserscustomers")
  async connectFundraiserscustomers(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiserscustomers: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraiserscustomers")
  async updateFundraiserscustomers(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiserscustomers: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraiserscustomers")
  async disconnectFundraiserscustomers(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiserscustomers: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/inboxReceiver")
  @ApiNestedQuery(InboxFindManyArgs)
  async findInboxReceiver(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Inbox[]> {
    const query = plainToClass(InboxFindManyArgs, request.query);
    const results = await this.service.findInboxReceiver(params.id, {
      ...query,
      select: {
        body: true,
        conversationUuid: true,
        createdAt: true,
        history: true,
        id: true,
        image: true,

        inboxReceiver: {
          select: {
            id: true,
          },
        },

        inboxSender: {
          select: {
            id: true,
          },
        },

        isRead: true,
        isReply: true,
        senderEmail: true,
        senderName: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inboxReceiver")
  async connectInboxReceiver(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: InboxWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inboxReceiver: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inboxReceiver")
  async updateInboxReceiver(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: InboxWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inboxReceiver: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inboxReceiver")
  async disconnectInboxReceiver(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: InboxWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inboxReceiver: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/inboxSender")
  @ApiNestedQuery(InboxFindManyArgs)
  async findInboxSender(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Inbox[]> {
    const query = plainToClass(InboxFindManyArgs, request.query);
    const results = await this.service.findInboxSender(params.id, {
      ...query,
      select: {
        body: true,
        conversationUuid: true,
        createdAt: true,
        history: true,
        id: true,
        image: true,

        inboxReceiver: {
          select: {
            id: true,
          },
        },

        inboxSender: {
          select: {
            id: true,
          },
        },

        isRead: true,
        isReply: true,
        senderEmail: true,
        senderName: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inboxSender")
  async connectInboxSender(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: InboxWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inboxSender: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inboxSender")
  async updateInboxSender(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: InboxWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inboxSender: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inboxSender")
  async disconnectInboxSender(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: InboxWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inboxSender: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        assigned: true,
        channel: true,
        channelUuid: true,
        createdAt: true,
        email: true,
        id: true,
        isPrivate: true,
        isRead: true,
        text: true,
        updatedAt: true,
        userName: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/notifications")
  @ApiNestedQuery(NotificationFindManyArgs)
  async findNotifications(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Notification[]> {
    const query = plainToClass(NotificationFindManyArgs, request.query);
    const results = await this.service.findNotifications(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        image: true,
        isRead: true,
        link: true,
        linkName: true,
        name: true,
        target: true,
        text: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/notifications")
  async connectNotifications(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: NotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notifications: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/notifications")
  async updateNotifications(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: NotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notifications: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/notifications")
  async disconnectNotifications(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: NotificationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      notifications: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        additional: true,
        address: true,
        atl: true,
        billingAddress: true,
        billingCountry: true,
        billingPostcode: true,
        billingState: true,
        billingSuburb: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        email: true,
        fullname: true,

        fundraiser: {
          select: {
            id: true,
          },
        },

        fundraiserTotal: true,
        id: true,
        orderId: true,
        orderTotal: true,

        ordersstatus: {
          select: {
            id: true,
          },
        },

        phone: true,
        postcode: true,
        profit: true,
        shippingTotal: true,
        state: true,
        suburb: true,

        supplier: {
          select: {
            id: true,
          },
        },

        supportNotes: true,
        tracking: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  async connectOrders(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  async updateOrders(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  async disconnectOrders(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/postcodes")
  @ApiNestedQuery(PostcodeFindManyArgs)
  async findPostcodes(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Postcode[]> {
    const query = plainToClass(PostcodeFindManyArgs, request.query);
    const results = await this.service.findPostcodes(params.id, {
      ...query,
      select: {
        code: true,
        createdAt: true,
        id: true,
        metro: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/postcodes")
  async connectPostcodes(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: PostcodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      postcodes: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/postcodes")
  async updatePostcodes(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: PostcodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      postcodes: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/postcodes")
  async disconnectPostcodes(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: PostcodeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      postcodes: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/products")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProducts(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProducts(params.id, {
      ...query,
      select: {
        active: true,
        adjustedSupplierPrice: true,
        alcohol: true,
        approved: true,
        archived: true,
        caseSize: true,
        closure: true,
        country: true,
        createdAt: true,
        description: true,
        fundraiserUuid: true,
        id: true,
        image: true,
        maxPrice: true,
        maxQty: true,
        minPrice: true,
        minQty: true,
        name: true,
        price: true,
        producer: true,
        region: true,
        sku: true,
        state: true,
        status: true,
        stock: true,
        stockAlert: true,
        stockact: true,
        stocknsw: true,
        stocknt: true,
        stockqld: true,
        stocksa: true,
        stocktas: true,
        stockvic: true,
        stockwa: true,
        supplierPrice: true,
        touched: true,
        typeField: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        uuid: true,
        varietal: true,
        vintage: true,
        volume: true,
        wholesalePrice: true,
        winemaker: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/products")
  async connectProducts(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/products")
  async updateProducts(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/products")
  async disconnectProducts(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      products: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/subscriptions")
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async findSubscriptions(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Subscription[]> {
    const query = plainToClass(SubscriptionFindManyArgs, request.query);
    const results = await this.service.findSubscriptions(params.id, {
      ...query,
      select: {
        access: true,
        alt: true,
        createdAt: true,
        id: true,
        image: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/subscriptions")
  async connectSubscriptions(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/subscriptions")
  async updateSubscriptions(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/subscriptions")
  async disconnectSubscriptions(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: SubscriptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subscriptions: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/supplier")
  @ApiNestedQuery(OrderFindManyArgs)
  async findSupplier(
    @common.Req() request: Request,
    @common.Param() params: UserRoleWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findSupplier(params.id, {
      ...query,
      select: {
        additional: true,
        address: true,
        atl: true,
        billingAddress: true,
        billingCountry: true,
        billingPostcode: true,
        billingState: true,
        billingSuburb: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        email: true,
        fullname: true,

        fundraiser: {
          select: {
            id: true,
          },
        },

        fundraiserTotal: true,
        id: true,
        orderId: true,
        orderTotal: true,

        ordersstatus: {
          select: {
            id: true,
          },
        },

        phone: true,
        postcode: true,
        profit: true,
        shippingTotal: true,
        state: true,
        suburb: true,

        supplier: {
          select: {
            id: true,
          },
        },

        supportNotes: true,
        tracking: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/supplier")
  async connectSupplier(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplier: {
        connect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/supplier")
  async updateSupplier(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplier: {
        set: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/supplier")
  async disconnectSupplier(
    @common.Param() params: UserRoleWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplier: {
        disconnect: body,
      },
    };
    await this.service.updateUserRole({
      where: params,
      data,
      select: { id: true },
    });
  }
}
