/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActivityListRelationFilter } from "../../activity/base/ActivityListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { CategoryListRelationFilter } from "../../category/base/CategoryListRelationFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { FundraiserListRelationFilter } from "../../fundraiser/base/FundraiserListRelationFilter";
import { FundraisersCustomerListRelationFilter } from "../../fundraisersCustomer/base/FundraisersCustomerListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { InboxListRelationFilter } from "../../inbox/base/InboxListRelationFilter";
import { MessageListRelationFilter } from "../../message/base/MessageListRelationFilter";
import { NotificationListRelationFilter } from "../../notification/base/NotificationListRelationFilter";
import { OrderListRelationFilter } from "../../order/base/OrderListRelationFilter";
import { PostcodeListRelationFilter } from "../../postcode/base/PostcodeListRelationFilter";
import { ProductListRelationFilter } from "../../product/base/ProductListRelationFilter";
import { EnumUserRoleRoles } from "./EnumUserRoleRoles";
import { SubscriptionListRelationFilter } from "../../subscription/base/SubscriptionListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class UserRoleWhereInput {
  @ApiProperty({
    required: false,
    type: () => ActivityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ActivityListRelationFilter)
  @IsOptional()
  @Field(() => ActivityListRelationFilter, {
    nullable: true,
  })
  activities?: ActivityListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CategoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CategoryListRelationFilter)
  @IsOptional()
  @Field(() => CategoryListRelationFilter, {
    nullable: true,
  })
  categories?: CategoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  emailNotification?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  enabled?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: () => FundraiserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FundraiserListRelationFilter)
  @IsOptional()
  @Field(() => FundraiserListRelationFilter, {
    nullable: true,
  })
  fundraisers?: FundraiserListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FundraiserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FundraiserListRelationFilter)
  @IsOptional()
  @Field(() => FundraiserListRelationFilter, {
    nullable: true,
  })
  fundraisersFundraisersSupplierUuidToUserRoles?: FundraiserListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FundraisersCustomerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FundraisersCustomerListRelationFilter)
  @IsOptional()
  @Field(() => FundraisersCustomerListRelationFilter, {
    nullable: true,
  })
  fundraiserscustomers?: FundraisersCustomerListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => InboxListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InboxListRelationFilter)
  @IsOptional()
  @Field(() => InboxListRelationFilter, {
    nullable: true,
  })
  inboxReceiver?: InboxListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => InboxListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InboxListRelationFilter)
  @IsOptional()
  @Field(() => InboxListRelationFilter, {
    nullable: true,
  })
  inboxSender?: InboxListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => MessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MessageListRelationFilter)
  @IsOptional()
  @Field(() => MessageListRelationFilter, {
    nullable: true,
  })
  messages?: MessageListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => NotificationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NotificationListRelationFilter)
  @IsOptional()
  @Field(() => NotificationListRelationFilter, {
    nullable: true,
  })
  notifications?: NotificationListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => OrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrderListRelationFilter)
  @IsOptional()
  @Field(() => OrderListRelationFilter, {
    nullable: true,
  })
  orders?: OrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PostcodeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PostcodeListRelationFilter)
  @IsOptional()
  @Field(() => PostcodeListRelationFilter, {
    nullable: true,
  })
  postcodes?: PostcodeListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProductListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ProductListRelationFilter)
  @IsOptional()
  @Field(() => ProductListRelationFilter, {
    nullable: true,
  })
  products?: ProductListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumUserRoleRoles,
  })
  @IsEnum(EnumUserRoleRoles)
  @IsOptional()
  @Field(() => EnumUserRoleRoles, {
    nullable: true,
  })
  roles?:
    | "ADMIN"
    | "MANAGER"
    | "SUPPLIER"
    | "REFERRER"
    | "CUSTOMER"
    | "SUPERADMIN"
    | "SUPPLIERADMIN";

  @ApiProperty({
    required: false,
    type: () => SubscriptionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SubscriptionListRelationFilter)
  @IsOptional()
  @Field(() => SubscriptionListRelationFilter, {
    nullable: true,
  })
  subscriptions?: SubscriptionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => OrderListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OrderListRelationFilter)
  @IsOptional()
  @Field(() => OrderListRelationFilter, {
    nullable: true,
  })
  supplier?: OrderListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  users?: UserWhereUniqueInput;
}

export { UserRoleWhereInput as UserRoleWhereInput };
