/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ActivityUpdateManyWithoutUserRolesInput } from "./ActivityUpdateManyWithoutUserRolesInput";
import { ValidateNested, IsOptional, IsBoolean, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { CategoryUpdateManyWithoutUserRolesInput } from "./CategoryUpdateManyWithoutUserRolesInput";
import { FundraiserUpdateManyWithoutUserRolesInput } from "./FundraiserUpdateManyWithoutUserRolesInput";
import { FundraisersCustomerUpdateManyWithoutUserRolesInput } from "./FundraisersCustomerUpdateManyWithoutUserRolesInput";
import { InboxUpdateManyWithoutUserRolesInput } from "./InboxUpdateManyWithoutUserRolesInput";
import { MessageUpdateManyWithoutUserRolesInput } from "./MessageUpdateManyWithoutUserRolesInput";
import { NotificationUpdateManyWithoutUserRolesInput } from "./NotificationUpdateManyWithoutUserRolesInput";
import { OrderUpdateManyWithoutUserRolesInput } from "./OrderUpdateManyWithoutUserRolesInput";
import { PostcodeUpdateManyWithoutUserRolesInput } from "./PostcodeUpdateManyWithoutUserRolesInput";
import { ProductUpdateManyWithoutUserRolesInput } from "./ProductUpdateManyWithoutUserRolesInput";
import { EnumUserRoleRoles } from "./EnumUserRoleRoles";
import { SubscriptionUpdateManyWithoutUserRolesInput } from "./SubscriptionUpdateManyWithoutUserRolesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class UserRoleUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ActivityUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => ActivityUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => ActivityUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  activities?: ActivityUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => CategoryUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => CategoryUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => CategoryUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  categories?: CategoryUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  emailNotification?: boolean;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  enabled?: boolean;

  @ApiProperty({
    required: false,
    type: () => FundraiserUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => FundraiserUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => FundraiserUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  fundraisers?: FundraiserUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => FundraiserUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => FundraiserUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => FundraiserUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  fundraisersFundraisersSupplierUuidToUserRoles?: FundraiserUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => FundraisersCustomerUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => FundraisersCustomerUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => FundraisersCustomerUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  fundraiserscustomers?: FundraisersCustomerUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => InboxUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => InboxUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => InboxUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  inboxReceiver?: InboxUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => InboxUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => InboxUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => InboxUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  inboxSender?: InboxUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => MessageUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => MessageUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => MessageUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  messages?: MessageUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => NotificationUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => NotificationUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => NotificationUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  notifications?: NotificationUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => PostcodeUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => PostcodeUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => PostcodeUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  postcodes?: PostcodeUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => ProductUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => ProductUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => ProductUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  products?: ProductUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    enum: EnumUserRoleRoles,
  })
  @IsEnum(EnumUserRoleRoles)
  @IsOptional()
  @Field(() => EnumUserRoleRoles, {
    nullable: true,
  })
  roles?:
    | "ADMIN"
    | "MANAGER"
    | "SUPPLIER"
    | "REFERRER"
    | "CUSTOMER"
    | "SUPERADMIN"
    | "SUPPLIERADMIN"
    | null;

  @ApiProperty({
    required: false,
    type: () => SubscriptionUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => SubscriptionUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutUserRolesInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutUserRolesInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutUserRolesInput, {
    nullable: true,
  })
  supplier?: OrderUpdateManyWithoutUserRolesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  users?: UserWhereUniqueInput | null;
}

export { UserRoleUpdateInput as UserRoleUpdateInput };
