/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserRole } from "./UserRole";
import { UserRoleCountArgs } from "./UserRoleCountArgs";
import { UserRoleFindManyArgs } from "./UserRoleFindManyArgs";
import { UserRoleFindUniqueArgs } from "./UserRoleFindUniqueArgs";
import { CreateUserRoleArgs } from "./CreateUserRoleArgs";
import { UpdateUserRoleArgs } from "./UpdateUserRoleArgs";
import { DeleteUserRoleArgs } from "./DeleteUserRoleArgs";
import { ActivityFindManyArgs } from "../../activity/base/ActivityFindManyArgs";
import { Activity } from "../../activity/base/Activity";
import { CategoryFindManyArgs } from "../../category/base/CategoryFindManyArgs";
import { Category } from "../../category/base/Category";
import { FundraiserFindManyArgs } from "../../fundraiser/base/FundraiserFindManyArgs";
import { Fundraiser } from "../../fundraiser/base/Fundraiser";
import { FundraisersCustomerFindManyArgs } from "../../fundraisersCustomer/base/FundraisersCustomerFindManyArgs";
import { FundraisersCustomer } from "../../fundraisersCustomer/base/FundraisersCustomer";
import { InboxFindManyArgs } from "../../inbox/base/InboxFindManyArgs";
import { Inbox } from "../../inbox/base/Inbox";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { NotificationFindManyArgs } from "../../notification/base/NotificationFindManyArgs";
import { Notification } from "../../notification/base/Notification";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { PostcodeFindManyArgs } from "../../postcode/base/PostcodeFindManyArgs";
import { Postcode } from "../../postcode/base/Postcode";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { SubscriptionFindManyArgs } from "../../subscription/base/SubscriptionFindManyArgs";
import { Subscription } from "../../subscription/base/Subscription";
import { User } from "../../user/base/User";
import { UserRoleService } from "../userRole.service";
@graphql.Resolver(() => UserRole)
export class UserRoleResolverBase {
  constructor(protected readonly service: UserRoleService) {}

  async _userRolesMeta(
    @graphql.Args() args: UserRoleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserRole])
  async userRoles(
    @graphql.Args() args: UserRoleFindManyArgs
  ): Promise<UserRole[]> {
    return this.service.userRoles(args);
  }

  @graphql.Query(() => UserRole, { nullable: true })
  async userRole(
    @graphql.Args() args: UserRoleFindUniqueArgs
  ): Promise<UserRole | null> {
    const result = await this.service.userRole(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserRole)
  async createUserRole(
    @graphql.Args() args: CreateUserRoleArgs
  ): Promise<UserRole> {
    return await this.service.createUserRole({
      ...args,
      data: {
        ...args.data,

        users: args.data.users
          ? {
              connect: args.data.users,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => UserRole)
  async updateUserRole(
    @graphql.Args() args: UpdateUserRoleArgs
  ): Promise<UserRole | null> {
    try {
      return await this.service.updateUserRole({
        ...args,
        data: {
          ...args.data,

          users: args.data.users
            ? {
                connect: args.data.users,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserRole)
  async deleteUserRole(
    @graphql.Args() args: DeleteUserRoleArgs
  ): Promise<UserRole | null> {
    try {
      return await this.service.deleteUserRole(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Activity], { name: "activities" })
  async findActivities(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: ActivityFindManyArgs
  ): Promise<Activity[]> {
    const results = await this.service.findActivities(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Category], { name: "categories" })
  async findCategories(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: CategoryFindManyArgs
  ): Promise<Category[]> {
    const results = await this.service.findCategories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Fundraiser], { name: "fundraisers" })
  async findFundraisers(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: FundraiserFindManyArgs
  ): Promise<Fundraiser[]> {
    const results = await this.service.findFundraisers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Fundraiser], {
    name: "fundraisersFundraisersSupplierUuidToUserRoles",
  })
  async findFundraisersFundraisersSupplierUuidToUserRoles(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: FundraiserFindManyArgs
  ): Promise<Fundraiser[]> {
    const results =
      await this.service.findFundraisersFundraisersSupplierUuidToUserRoles(
        parent.id,
        args
      );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [FundraisersCustomer], {
    name: "fundraiserscustomers",
  })
  async findFundraiserscustomers(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: FundraisersCustomerFindManyArgs
  ): Promise<FundraisersCustomer[]> {
    const results = await this.service.findFundraiserscustomers(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Inbox], { name: "inboxReceiver" })
  async findInboxReceiver(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: InboxFindManyArgs
  ): Promise<Inbox[]> {
    const results = await this.service.findInboxReceiver(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Inbox], { name: "inboxSender" })
  async findInboxSender(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: InboxFindManyArgs
  ): Promise<Inbox[]> {
    const results = await this.service.findInboxSender(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Message], { name: "messages" })
  async findMessages(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Notification], { name: "notifications" })
  async findNotifications(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: NotificationFindManyArgs
  ): Promise<Notification[]> {
    const results = await this.service.findNotifications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Order], { name: "orders" })
  async findOrders(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Postcode], { name: "postcodes" })
  async findPostcodes(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: PostcodeFindManyArgs
  ): Promise<Postcode[]> {
    const results = await this.service.findPostcodes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Product], { name: "products" })
  async findProducts(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: ProductFindManyArgs
  ): Promise<Product[]> {
    const results = await this.service.findProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Subscription], { name: "subscriptions" })
  async findSubscriptions(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: SubscriptionFindManyArgs
  ): Promise<Subscription[]> {
    const results = await this.service.findSubscriptions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Order], { name: "supplier" })
  async findSupplier(
    @graphql.Parent() parent: UserRole,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findSupplier(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "users",
  })
  async getUsers(@graphql.Parent() parent: UserRole): Promise<User | null> {
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
