import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FundraisersPromotionListRelationFilter } from "../fundraisersPromotion/FundraisersPromotionListRelationFilter";
import { FundraisersCustomerListRelationFilter } from "../fundraisersCustomer/FundraisersCustomerListRelationFilter";
import { FundraisersImageWhereUniqueInput } from "../fundraisersImage/FundraisersImageWhereUniqueInput";
import { OrderListRelationFilter } from "../order/OrderListRelationFilter";
import { FundraisersProductListRelationFilter } from "../fundraisersProduct/FundraisersProductListRelationFilter";
import { FundraisersStatusWhereUniqueInput } from "../fundraisersStatus/FundraisersStatusWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { TopicWhereUniqueInput } from "../topic/TopicWhereUniqueInput";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";

export type FundraiserWhereInput = {
  createdAt?: DateTimeFilter;
  description?: StringNullableFilter;
  endDate?: DateTimeFilter;
  fundraisersPromotions?: FundraisersPromotionListRelationFilter;
  fundraiserscustomers?: FundraisersCustomerListRelationFilter;
  fundraisersimages?: FundraisersImageWhereUniqueInput;
  fundraisersorders?: OrderListRelationFilter;
  fundraisersproducts?: FundraisersProductListRelationFilter;
  fundraisersstatus?: FundraisersStatusWhereUniqueInput;
  id?: StringFilter;
  image?: StringNullableFilter;
  link?: StringNullableFilter;
  postcode?: StringNullableFilter;
  startDate?: DateTimeFilter;
  subscribed?: BooleanFilter;
  suburb?: StringNullableFilter;
  target?: IntNullableFilter;
  title?: StringNullableFilter;
  topic?: StringNullableFilter;
  topics?: TopicWhereUniqueInput;
  updatedAt?: DateTimeFilter;
  userRoles?: UserRoleWhereUniqueInput;
  userRolesFundraisersSupplierUuidToUserRoles?: UserRoleWhereUniqueInput;
};
