import { FundraisersProductCreateNestedManyWithoutProductsInput } from "./FundraisersProductCreateNestedManyWithoutProductsInput";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";

export type ProductCreateInput = {
  active: boolean;
  adjustedSupplierPrice?: number | null;
  alcohol?: number | null;
  approved: boolean;
  archived: boolean;
  caseSize?: number | null;
  closure?: string | null;
  country?: string | null;
  description?: string | null;
  fundraiserUuid?: string | null;
  fundraisersProducts?: FundraisersProductCreateNestedManyWithoutProductsInput;
  image?: string | null;
  maxPrice?: number | null;
  maxQty?: number | null;
  minPrice?: number | null;
  minQty?: number | null;
  name: string;
  price?: number | null;
  producer?: string | null;
  region?: string | null;
  sku?: string | null;
  state?: string | null;
  status?: string | null;
  stock?: number | null;
  stockAlert?: number | null;
  stockact?: number | null;
  stocknsw?: number | null;
  stocknt?: number | null;
  stockqld?: number | null;
  stocksa?: number | null;
  stocktas?: number | null;
  stockvic?: number | null;
  stockwa?: number | null;
  supplierPrice?: number | null;
  touched: boolean;
  typeField?: string | null;
  userRoles?: UserRoleWhereUniqueInput | null;
  uuid: string;
  varietal?: string | null;
  vintage?: string | null;
  volume?: number | null;
  wholesalePrice?: number | null;
  winemaker?: string | null;
};
