import { BooleanFilter } from "../../util/BooleanFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { FundraisersProductListRelationFilter } from "../fundraisersProduct/FundraisersProductListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { StringFilter } from "../../util/StringFilter";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";

export type ProductWhereInput = {
  active?: BooleanFilter;
  adjustedSupplierPrice?: FloatNullableFilter;
  alcohol?: IntNullableFilter;
  approved?: BooleanFilter;
  archived?: BooleanFilter;
  caseSize?: IntNullableFilter;
  closure?: StringNullableFilter;
  country?: StringNullableFilter;
  createdAt?: DateTimeFilter;
  description?: StringNullableFilter;
  fundraiserUuid?: StringNullableFilter;
  fundraisersProducts?: FundraisersProductListRelationFilter;
  id?: IntFilter;
  image?: StringNullableFilter;
  maxPrice?: FloatNullableFilter;
  maxQty?: IntNullableFilter;
  minPrice?: FloatNullableFilter;
  minQty?: IntNullableFilter;
  name?: StringFilter;
  price?: FloatNullableFilter;
  producer?: StringNullableFilter;
  region?: StringNullableFilter;
  sku?: StringNullableFilter;
  state?: StringNullableFilter;
  status?: StringNullableFilter;
  stock?: IntNullableFilter;
  stockAlert?: IntNullableFilter;
  stockact?: IntNullableFilter;
  stocknsw?: IntNullableFilter;
  stocknt?: IntNullableFilter;
  stockqld?: IntNullableFilter;
  stocksa?: IntNullableFilter;
  stocktas?: IntNullableFilter;
  stockvic?: IntNullableFilter;
  stockwa?: IntNullableFilter;
  supplierPrice?: FloatNullableFilter;
  touched?: BooleanFilter;
  typeField?: StringNullableFilter;
  updatedAt?: DateTimeFilter;
  userRoles?: UserRoleWhereUniqueInput;
  uuid?: StringFilter;
  varietal?: StringNullableFilter;
  vintage?: StringNullableFilter;
  volume?: IntNullableFilter;
  wholesalePrice?: FloatNullableFilter;
  winemaker?: StringNullableFilter;
};
