import { FundraisersProduct } from "../fundraisersProduct/FundraisersProduct";
import { UserRole } from "../userRole/UserRole";

export type Product = {
  active: boolean;
  adjustedSupplierPrice: number | null;
  alcohol: number | null;
  approved: boolean;
  archived: boolean;
  caseSize: number | null;
  closure: string | null;
  country: string | null;
  createdAt: Date;
  description: string | null;
  fundraiserUuid: string | null;
  fundraisersProducts?: Array<FundraisersProduct>;
  id: number;
  image: string | null;
  maxPrice: number | null;
  maxQty: number | null;
  minPrice: number | null;
  minQty: number | null;
  name: string;
  price: number | null;
  producer: string | null;
  region: string | null;
  sku: string | null;
  state: string | null;
  status: string | null;
  stock: number | null;
  stockAlert: number | null;
  stockact: number | null;
  stocknsw: number | null;
  stocknt: number | null;
  stockqld: number | null;
  stocksa: number | null;
  stocktas: number | null;
  stockvic: number | null;
  stockwa: number | null;
  supplierPrice: number | null;
  touched: boolean;
  typeField: string | null;
  updatedAt: Date;
  userRoles?: UserRole | null;
  uuid: string;
  varietal: string | null;
  vintage: string | null;
  volume: number | null;
  wholesalePrice: number | null;
  winemaker: string | null;
};
