/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  CategoriesImage as PrismaCategoriesImage,
  Category as PrismaCategory,
} from "@prisma/client";

export class CategoriesImageServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CategoriesImageCountArgs, "select">
  ): Promise<number> {
    return this.prisma.categoriesImage.count(args);
  }

  async categoriesImages(
    args: Prisma.CategoriesImageFindManyArgs
  ): Promise<PrismaCategoriesImage[]> {
    return this.prisma.categoriesImage.findMany(args);
  }
  async categoriesImage(
    args: Prisma.CategoriesImageFindUniqueArgs
  ): Promise<PrismaCategoriesImage | null> {
    return this.prisma.categoriesImage.findUnique(args);
  }
  async createCategoriesImage(
    args: Prisma.CategoriesImageCreateArgs
  ): Promise<PrismaCategoriesImage> {
    return this.prisma.categoriesImage.create(args);
  }
  async updateCategoriesImage(
    args: Prisma.CategoriesImageUpdateArgs
  ): Promise<PrismaCategoriesImage> {
    return this.prisma.categoriesImage.update(args);
  }
  async deleteCategoriesImage(
    args: Prisma.CategoriesImageDeleteArgs
  ): Promise<PrismaCategoriesImage> {
    return this.prisma.categoriesImage.delete(args);
  }

  async findCategories(
    parentId: string,
    args: Prisma.CategoryFindManyArgs
  ): Promise<PrismaCategory[]> {
    return this.prisma.categoriesImage
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .categories(args);
  }
}
