/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CategoriesImage } from "./CategoriesImage";
import { CategoriesImageCountArgs } from "./CategoriesImageCountArgs";
import { CategoriesImageFindManyArgs } from "./CategoriesImageFindManyArgs";
import { CategoriesImageFindUniqueArgs } from "./CategoriesImageFindUniqueArgs";
import { CreateCategoriesImageArgs } from "./CreateCategoriesImageArgs";
import { UpdateCategoriesImageArgs } from "./UpdateCategoriesImageArgs";
import { DeleteCategoriesImageArgs } from "./DeleteCategoriesImageArgs";
import { CategoryFindManyArgs } from "../../category/base/CategoryFindManyArgs";
import { Category } from "../../category/base/Category";
import { CategoriesImageService } from "../categoriesImage.service";
@graphql.Resolver(() => CategoriesImage)
export class CategoriesImageResolverBase {
  constructor(protected readonly service: CategoriesImageService) {}

  async _categoriesImagesMeta(
    @graphql.Args() args: CategoriesImageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CategoriesImage])
  async categoriesImages(
    @graphql.Args() args: CategoriesImageFindManyArgs
  ): Promise<CategoriesImage[]> {
    return this.service.categoriesImages(args);
  }

  @graphql.Query(() => CategoriesImage, { nullable: true })
  async categoriesImage(
    @graphql.Args() args: CategoriesImageFindUniqueArgs
  ): Promise<CategoriesImage | null> {
    const result = await this.service.categoriesImage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CategoriesImage)
  async createCategoriesImage(
    @graphql.Args() args: CreateCategoriesImageArgs
  ): Promise<CategoriesImage> {
    return await this.service.createCategoriesImage({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => CategoriesImage)
  async updateCategoriesImage(
    @graphql.Args() args: UpdateCategoriesImageArgs
  ): Promise<CategoriesImage | null> {
    try {
      return await this.service.updateCategoriesImage({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CategoriesImage)
  async deleteCategoriesImage(
    @graphql.Args() args: DeleteCategoriesImageArgs
  ): Promise<CategoriesImage | null> {
    try {
      return await this.service.deleteCategoriesImage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Category], { name: "categories" })
  async findCategories(
    @graphql.Parent() parent: CategoriesImage,
    @graphql.Args() args: CategoryFindManyArgs
  ): Promise<Category[]> {
    const results = await this.service.findCategories(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
