/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CategoriesImageService } from "../categoriesImage.service";
import { CategoriesImageCreateInput } from "./CategoriesImageCreateInput";
import { CategoriesImage } from "./CategoriesImage";
import { CategoriesImageFindManyArgs } from "./CategoriesImageFindManyArgs";
import { CategoriesImageWhereUniqueInput } from "./CategoriesImageWhereUniqueInput";
import { CategoriesImageUpdateInput } from "./CategoriesImageUpdateInput";
import { CategoryFindManyArgs } from "../../category/base/CategoryFindManyArgs";
import { Category } from "../../category/base/Category";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";

export class CategoriesImageControllerBase {
  constructor(protected readonly service: CategoriesImageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CategoriesImage })
  async createCategoriesImage(
    @common.Body() data: CategoriesImageCreateInput
  ): Promise<CategoriesImage> {
    return await this.service.createCategoriesImage({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CategoriesImage] })
  @ApiNestedQuery(CategoriesImageFindManyArgs)
  async categoriesImages(
    @common.Req() request: Request
  ): Promise<CategoriesImage[]> {
    const args = plainToClass(CategoriesImageFindManyArgs, request.query);
    return this.service.categoriesImages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CategoriesImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async categoriesImage(
    @common.Param() params: CategoriesImageWhereUniqueInput
  ): Promise<CategoriesImage | null> {
    const result = await this.service.categoriesImage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CategoriesImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCategoriesImage(
    @common.Param() params: CategoriesImageWhereUniqueInput,
    @common.Body() data: CategoriesImageUpdateInput
  ): Promise<CategoriesImage | null> {
    try {
      return await this.service.updateCategoriesImage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          path: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CategoriesImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCategoriesImage(
    @common.Param() params: CategoriesImageWhereUniqueInput
  ): Promise<CategoriesImage | null> {
    try {
      return await this.service.deleteCategoriesImage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          path: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/categories")
  @ApiNestedQuery(CategoryFindManyArgs)
  async findCategories(
    @common.Req() request: Request,
    @common.Param() params: CategoriesImageWhereUniqueInput
  ): Promise<Category[]> {
    const query = plainToClass(CategoryFindManyArgs, request.query);
    const results = await this.service.findCategories(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        quickStarter: true,
        title: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/categories")
  async connectCategories(
    @common.Param() params: CategoriesImageWhereUniqueInput,
    @common.Body() body: CategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categories: {
        connect: body,
      },
    };
    await this.service.updateCategoriesImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/categories")
  async updateCategories(
    @common.Param() params: CategoriesImageWhereUniqueInput,
    @common.Body() body: CategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categories: {
        set: body,
      },
    };
    await this.service.updateCategoriesImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/categories")
  async disconnectCategories(
    @common.Param() params: CategoriesImageWhereUniqueInput,
    @common.Body() body: CategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categories: {
        disconnect: body,
      },
    };
    await this.service.updateCategoriesImage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
