/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FundraisersCustomer as PrismaFundraisersCustomer,
  Fundraiser as PrismaFundraiser,
  FundraisersStatus as PrismaFundraisersStatus,
  UserRole as PrismaUserRole,
} from "@prisma/client";

export class FundraisersCustomerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FundraisersCustomerCountArgs, "select">
  ): Promise<number> {
    return this.prisma.fundraisersCustomer.count(args);
  }

  async fundraisersCustomers(
    args: Prisma.FundraisersCustomerFindManyArgs
  ): Promise<PrismaFundraisersCustomer[]> {
    return this.prisma.fundraisersCustomer.findMany(args);
  }
  async fundraisersCustomer(
    args: Prisma.FundraisersCustomerFindUniqueArgs
  ): Promise<PrismaFundraisersCustomer | null> {
    return this.prisma.fundraisersCustomer.findUnique(args);
  }
  async createFundraisersCustomer(
    args: Prisma.FundraisersCustomerCreateArgs
  ): Promise<PrismaFundraisersCustomer> {
    return this.prisma.fundraisersCustomer.create(args);
  }
  async updateFundraisersCustomer(
    args: Prisma.FundraisersCustomerUpdateArgs
  ): Promise<PrismaFundraisersCustomer> {
    return this.prisma.fundraisersCustomer.update(args);
  }
  async deleteFundraisersCustomer(
    args: Prisma.FundraisersCustomerDeleteArgs
  ): Promise<PrismaFundraisersCustomer> {
    return this.prisma.fundraisersCustomer.delete(args);
  }

  async getFundraiser(parentId: string): Promise<PrismaFundraiser | null> {
    return this.prisma.fundraisersCustomer
      .findUnique({
        where: { id: parentId },
      })
      .fundraiser();
  }

  async getFundraisersStatus(
    parentId: string
  ): Promise<PrismaFundraisersStatus | null> {
    return this.prisma.fundraisersCustomer
      .findUnique({
        where: { id: parentId },
      })
      .fundraisersStatus();
  }

  async getUserRoles(parentId: string): Promise<PrismaUserRole | null> {
    return this.prisma.fundraisersCustomer
      .findUnique({
        where: { id: parentId },
      })
      .userRoles();
  }
}
