/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FundraisersCustomer } from "./FundraisersCustomer";
import { FundraisersCustomerCountArgs } from "./FundraisersCustomerCountArgs";
import { FundraisersCustomerFindManyArgs } from "./FundraisersCustomerFindManyArgs";
import { FundraisersCustomerFindUniqueArgs } from "./FundraisersCustomerFindUniqueArgs";
import { CreateFundraisersCustomerArgs } from "./CreateFundraisersCustomerArgs";
import { UpdateFundraisersCustomerArgs } from "./UpdateFundraisersCustomerArgs";
import { DeleteFundraisersCustomerArgs } from "./DeleteFundraisersCustomerArgs";
import { Fundraiser } from "../../fundraiser/base/Fundraiser";
import { FundraisersStatus } from "../../fundraisersStatus/base/FundraisersStatus";
import { UserRole } from "../../userRole/base/UserRole";
import { FundraisersCustomerService } from "../fundraisersCustomer.service";
@graphql.Resolver(() => FundraisersCustomer)
export class FundraisersCustomerResolverBase {
  constructor(protected readonly service: FundraisersCustomerService) {}

  async _fundraisersCustomersMeta(
    @graphql.Args() args: FundraisersCustomerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FundraisersCustomer])
  async fundraisersCustomers(
    @graphql.Args() args: FundraisersCustomerFindManyArgs
  ): Promise<FundraisersCustomer[]> {
    return this.service.fundraisersCustomers(args);
  }

  @graphql.Query(() => FundraisersCustomer, { nullable: true })
  async fundraisersCustomer(
    @graphql.Args() args: FundraisersCustomerFindUniqueArgs
  ): Promise<FundraisersCustomer | null> {
    const result = await this.service.fundraisersCustomer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FundraisersCustomer)
  async createFundraisersCustomer(
    @graphql.Args() args: CreateFundraisersCustomerArgs
  ): Promise<FundraisersCustomer> {
    return await this.service.createFundraisersCustomer({
      ...args,
      data: {
        ...args.data,

        fundraiser: args.data.fundraiser
          ? {
              connect: args.data.fundraiser,
            }
          : undefined,

        fundraisersStatus: args.data.fundraisersStatus
          ? {
              connect: args.data.fundraisersStatus,
            }
          : undefined,

        userRoles: args.data.userRoles
          ? {
              connect: args.data.userRoles,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FundraisersCustomer)
  async updateFundraisersCustomer(
    @graphql.Args() args: UpdateFundraisersCustomerArgs
  ): Promise<FundraisersCustomer | null> {
    try {
      return await this.service.updateFundraisersCustomer({
        ...args,
        data: {
          ...args.data,

          fundraiser: args.data.fundraiser
            ? {
                connect: args.data.fundraiser,
              }
            : undefined,

          fundraisersStatus: args.data.fundraisersStatus
            ? {
                connect: args.data.fundraisersStatus,
              }
            : undefined,

          userRoles: args.data.userRoles
            ? {
                connect: args.data.userRoles,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FundraisersCustomer)
  async deleteFundraisersCustomer(
    @graphql.Args() args: DeleteFundraisersCustomerArgs
  ): Promise<FundraisersCustomer | null> {
    try {
      return await this.service.deleteFundraisersCustomer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Fundraiser, {
    nullable: true,
    name: "fundraiser",
  })
  async getFundraiser(
    @graphql.Parent() parent: FundraisersCustomer
  ): Promise<Fundraiser | null> {
    const result = await this.service.getFundraiser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => FundraisersStatus, {
    nullable: true,
    name: "fundraisersStatus",
  })
  async getFundraisersStatus(
    @graphql.Parent() parent: FundraisersCustomer
  ): Promise<FundraisersStatus | null> {
    const result = await this.service.getFundraisersStatus(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => UserRole, {
    nullable: true,
    name: "userRoles",
  })
  async getUserRoles(
    @graphql.Parent() parent: FundraisersCustomer
  ): Promise<UserRole | null> {
    const result = await this.service.getUserRoles(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
