/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PromotionsProductListRelationFilter } from "../../promotionsProduct/base/PromotionsProductListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntFilter } from "../../util/IntFilter";
import { FundraisersPromotionListRelationFilter } from "../../fundraisersPromotion/base/FundraisersPromotionListRelationFilter";
import { PromotionsImageWhereUniqueInput } from "../../promotionsImage/base/PromotionsImageWhereUniqueInput";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { EnumPromotionPromotionMethod } from "./EnumPromotionPromotionMethod";
import { EnumPromotionPromotionStatus } from "./EnumPromotionPromotionStatus";
import { EnumPromotionPromotionType } from "./EnumPromotionPromotionType";

@InputType()
class PromotionWhereInput {
  @ApiProperty({
    required: false,
    type: () => PromotionsProductListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PromotionsProductListRelationFilter)
  @IsOptional()
  @Field(() => PromotionsProductListRelationFilter, {
    nullable: true,
  })
  categoriesproducts?: PromotionsProductListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  description?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  discount?: IntFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  endDate?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  excerpt?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => FundraisersPromotionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FundraisersPromotionListRelationFilter)
  @IsOptional()
  @Field(() => FundraisersPromotionListRelationFilter, {
    nullable: true,
  })
  fundraisersPromotions?: FundraisersPromotionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PromotionsImageWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PromotionsImageWhereUniqueInput)
  @IsOptional()
  @Field(() => PromotionsImageWhereUniqueInput, {
    nullable: true,
  })
  image?: PromotionsImageWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  max?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  min?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumPromotionPromotionMethod,
  })
  @IsEnum(EnumPromotionPromotionMethod)
  @IsOptional()
  @Field(() => EnumPromotionPromotionMethod, {
    nullable: true,
  })
  promotionMethod?: "DOLLAR" | "PERCENTAGE";

  @ApiProperty({
    required: false,
    enum: EnumPromotionPromotionStatus,
  })
  @IsEnum(EnumPromotionPromotionStatus)
  @IsOptional()
  @Field(() => EnumPromotionPromotionStatus, {
    nullable: true,
  })
  promotionStatus?: "ACTIVE" | "INACTIVE" | "EXPIRES_SOON" | "EXPIRED";

  @ApiProperty({
    required: false,
    enum: EnumPromotionPromotionType,
  })
  @IsEnum(EnumPromotionPromotionType)
  @IsOptional()
  @Field(() => EnumPromotionPromotionType, {
    nullable: true,
  })
  promotionType?: "FUNDRAISER" | "PARTNER";

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  startDate?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;
}

export { PromotionWhereInput as PromotionWhereInput };
