/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PromotionService } from "../promotion.service";
import { PromotionCreateInput } from "./PromotionCreateInput";
import { Promotion } from "./Promotion";
import { PromotionFindManyArgs } from "./PromotionFindManyArgs";
import { PromotionWhereUniqueInput } from "./PromotionWhereUniqueInput";
import { PromotionUpdateInput } from "./PromotionUpdateInput";
import { PromotionsProductFindManyArgs } from "../../promotionsProduct/base/PromotionsProductFindManyArgs";
import { PromotionsProduct } from "../../promotionsProduct/base/PromotionsProduct";
import { PromotionsProductWhereUniqueInput } from "../../promotionsProduct/base/PromotionsProductWhereUniqueInput";
import { FundraisersPromotionFindManyArgs } from "../../fundraisersPromotion/base/FundraisersPromotionFindManyArgs";
import { FundraisersPromotion } from "../../fundraisersPromotion/base/FundraisersPromotion";
import { FundraisersPromotionWhereUniqueInput } from "../../fundraisersPromotion/base/FundraisersPromotionWhereUniqueInput";

export class PromotionControllerBase {
  constructor(protected readonly service: PromotionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Promotion })
  async createPromotion(
    @common.Body() data: PromotionCreateInput
  ): Promise<Promotion> {
    return await this.service.createPromotion({
      data: {
        ...data,

        image: data.image
          ? {
              connect: data.image,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        discount: true,
        endDate: true,
        excerpt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        max: true,
        min: true,
        name: true,
        promotionMethod: true,
        promotionStatus: true,
        promotionType: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Promotion] })
  @ApiNestedQuery(PromotionFindManyArgs)
  async promotions(@common.Req() request: Request): Promise<Promotion[]> {
    const args = plainToClass(PromotionFindManyArgs, request.query);
    return this.service.promotions({
      ...args,
      select: {
        createdAt: true,
        description: true,
        discount: true,
        endDate: true,
        excerpt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        max: true,
        min: true,
        name: true,
        promotionMethod: true,
        promotionStatus: true,
        promotionType: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Promotion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async promotion(
    @common.Param() params: PromotionWhereUniqueInput
  ): Promise<Promotion | null> {
    const result = await this.service.promotion({
      where: params,
      select: {
        createdAt: true,
        description: true,
        discount: true,
        endDate: true,
        excerpt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        max: true,
        min: true,
        name: true,
        promotionMethod: true,
        promotionStatus: true,
        promotionType: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Promotion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePromotion(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() data: PromotionUpdateInput
  ): Promise<Promotion | null> {
    try {
      return await this.service.updatePromotion({
        where: params,
        data: {
          ...data,

          image: data.image
            ? {
                connect: data.image,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          discount: true,
          endDate: true,
          excerpt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          max: true,
          min: true,
          name: true,
          promotionMethod: true,
          promotionStatus: true,
          promotionType: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Promotion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePromotion(
    @common.Param() params: PromotionWhereUniqueInput
  ): Promise<Promotion | null> {
    try {
      return await this.service.deletePromotion({
        where: params,
        select: {
          createdAt: true,
          description: true,
          discount: true,
          endDate: true,
          excerpt: true,
          id: true,

          image: {
            select: {
              id: true,
            },
          },

          max: true,
          min: true,
          name: true,
          promotionMethod: true,
          promotionStatus: true,
          promotionType: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/categoriesproducts")
  @ApiNestedQuery(PromotionsProductFindManyArgs)
  async findCategoriesproducts(
    @common.Req() request: Request,
    @common.Param() params: PromotionWhereUniqueInput
  ): Promise<PromotionsProduct[]> {
    const query = plainToClass(PromotionsProductFindManyArgs, request.query);
    const results = await this.service.findCategoriesproducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        productUuid: true,

        promotion: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/categoriesproducts")
  async connectCategoriesproducts(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() body: PromotionsProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoriesproducts: {
        connect: body,
      },
    };
    await this.service.updatePromotion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/categoriesproducts")
  async updateCategoriesproducts(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() body: PromotionsProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoriesproducts: {
        set: body,
      },
    };
    await this.service.updatePromotion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/categoriesproducts")
  async disconnectCategoriesproducts(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() body: PromotionsProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoriesproducts: {
        disconnect: body,
      },
    };
    await this.service.updatePromotion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraisersPromotions")
  @ApiNestedQuery(FundraisersPromotionFindManyArgs)
  async findFundraisersPromotions(
    @common.Req() request: Request,
    @common.Param() params: PromotionWhereUniqueInput
  ): Promise<FundraisersPromotion[]> {
    const query = plainToClass(FundraisersPromotionFindManyArgs, request.query);
    const results = await this.service.findFundraisersPromotions(params.id, {
      ...query,
      select: {
        createdAt: true,

        fundraisers: {
          select: {
            id: true,
          },
        },

        id: true,

        promotions: {
          select: {
            id: true,
          },
        },

        source: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisersPromotions")
  async connectFundraisersPromotions(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() body: FundraisersPromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersPromotions: {
        connect: body,
      },
    };
    await this.service.updatePromotion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisersPromotions")
  async updateFundraisersPromotions(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() body: FundraisersPromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersPromotions: {
        set: body,
      },
    };
    await this.service.updatePromotion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisersPromotions")
  async disconnectFundraisersPromotions(
    @common.Param() params: PromotionWhereUniqueInput,
    @common.Body() body: FundraisersPromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersPromotions: {
        disconnect: body,
      },
    };
    await this.service.updatePromotion({
      where: params,
      data,
      select: { id: true },
    });
  }
}
