/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PromotionsProductUpdateManyWithoutPromotionsInput } from "./PromotionsProductUpdateManyWithoutPromotionsInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Max,
  IsNumber,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { FundraisersPromotionUpdateManyWithoutPromotionsInput } from "./FundraisersPromotionUpdateManyWithoutPromotionsInput";
import { PromotionsImageWhereUniqueInput } from "../../promotionsImage/base/PromotionsImageWhereUniqueInput";
import { EnumPromotionPromotionMethod } from "./EnumPromotionPromotionMethod";
import { EnumPromotionPromotionStatus } from "./EnumPromotionPromotionStatus";
import { EnumPromotionPromotionType } from "./EnumPromotionPromotionType";

@InputType()
class PromotionUpdateInput {
  @ApiProperty({
    required: false,
    type: () => PromotionsProductUpdateManyWithoutPromotionsInput,
  })
  @ValidateNested()
  @Type(() => PromotionsProductUpdateManyWithoutPromotionsInput)
  @IsOptional()
  @Field(() => PromotionsProductUpdateManyWithoutPromotionsInput, {
    nullable: true,
  })
  categoriesproducts?: PromotionsProductUpdateManyWithoutPromotionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  discount?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  excerpt?: string;

  @ApiProperty({
    required: false,
    type: () => FundraisersPromotionUpdateManyWithoutPromotionsInput,
  })
  @ValidateNested()
  @Type(() => FundraisersPromotionUpdateManyWithoutPromotionsInput)
  @IsOptional()
  @Field(() => FundraisersPromotionUpdateManyWithoutPromotionsInput, {
    nullable: true,
  })
  fundraisersPromotions?: FundraisersPromotionUpdateManyWithoutPromotionsInput;

  @ApiProperty({
    required: false,
    type: () => PromotionsImageWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PromotionsImageWhereUniqueInput)
  @IsOptional()
  @Field(() => PromotionsImageWhereUniqueInput, {
    nullable: true,
  })
  image?: PromotionsImageWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  max?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  min?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    enum: EnumPromotionPromotionMethod,
  })
  @IsEnum(EnumPromotionPromotionMethod)
  @IsOptional()
  @Field(() => EnumPromotionPromotionMethod, {
    nullable: true,
  })
  promotionMethod?: "DOLLAR" | "PERCENTAGE";

  @ApiProperty({
    required: false,
    enum: EnumPromotionPromotionStatus,
  })
  @IsEnum(EnumPromotionPromotionStatus)
  @IsOptional()
  @Field(() => EnumPromotionPromotionStatus, {
    nullable: true,
  })
  promotionStatus?: "ACTIVE" | "INACTIVE" | "EXPIRES_SOON" | "EXPIRED";

  @ApiProperty({
    required: false,
    enum: EnumPromotionPromotionType,
  })
  @IsEnum(EnumPromotionPromotionType)
  @IsOptional()
  @Field(() => EnumPromotionPromotionType, {
    nullable: true,
  })
  promotionType?: "FUNDRAISER" | "PARTNER";
}

export { PromotionUpdateInput as PromotionUpdateInput };
