/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PromotionsProductCreateNestedManyWithoutPromotionsInput } from "./PromotionsProductCreateNestedManyWithoutPromotionsInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Max,
  IsNumber,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { FundraisersPromotionCreateNestedManyWithoutPromotionsInput } from "./FundraisersPromotionCreateNestedManyWithoutPromotionsInput";
import { PromotionsImageWhereUniqueInput } from "../../promotionsImage/base/PromotionsImageWhereUniqueInput";
import { EnumPromotionPromotionMethod } from "./EnumPromotionPromotionMethod";
import { EnumPromotionPromotionStatus } from "./EnumPromotionPromotionStatus";
import { EnumPromotionPromotionType } from "./EnumPromotionPromotionType";

@InputType()
class PromotionCreateInput {
  @ApiProperty({
    required: false,
    type: () => PromotionsProductCreateNestedManyWithoutPromotionsInput,
  })
  @ValidateNested()
  @Type(() => PromotionsProductCreateNestedManyWithoutPromotionsInput)
  @IsOptional()
  @Field(() => PromotionsProductCreateNestedManyWithoutPromotionsInput, {
    nullable: true,
  })
  categoriesproducts?: PromotionsProductCreateNestedManyWithoutPromotionsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  discount!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  excerpt!: string;

  @ApiProperty({
    required: false,
    type: () => FundraisersPromotionCreateNestedManyWithoutPromotionsInput,
  })
  @ValidateNested()
  @Type(() => FundraisersPromotionCreateNestedManyWithoutPromotionsInput)
  @IsOptional()
  @Field(() => FundraisersPromotionCreateNestedManyWithoutPromotionsInput, {
    nullable: true,
  })
  fundraisersPromotions?: FundraisersPromotionCreateNestedManyWithoutPromotionsInput;

  @ApiProperty({
    required: false,
    type: () => PromotionsImageWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PromotionsImageWhereUniqueInput)
  @IsOptional()
  @Field(() => PromotionsImageWhereUniqueInput, {
    nullable: true,
  })
  image?: PromotionsImageWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  max?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  min?: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    enum: EnumPromotionPromotionMethod,
  })
  @IsEnum(EnumPromotionPromotionMethod)
  @Field(() => EnumPromotionPromotionMethod)
  promotionMethod!: "DOLLAR" | "PERCENTAGE";

  @ApiProperty({
    required: true,
    enum: EnumPromotionPromotionStatus,
  })
  @IsEnum(EnumPromotionPromotionStatus)
  @Field(() => EnumPromotionPromotionStatus)
  promotionStatus!: "ACTIVE" | "INACTIVE" | "EXPIRES_SOON" | "EXPIRED";

  @ApiProperty({
    required: true,
    enum: EnumPromotionPromotionType,
  })
  @IsEnum(EnumPromotionPromotionType)
  @Field(() => EnumPromotionPromotionType)
  promotionType!: "FUNDRAISER" | "PARTNER";
}

export { PromotionCreateInput as PromotionCreateInput };
