/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FundraisersProductService } from "../fundraisersProduct.service";
import { FundraisersProductCreateInput } from "./FundraisersProductCreateInput";
import { FundraisersProduct } from "./FundraisersProduct";
import { FundraisersProductFindManyArgs } from "./FundraisersProductFindManyArgs";
import { FundraisersProductWhereUniqueInput } from "./FundraisersProductWhereUniqueInput";
import { FundraisersProductUpdateInput } from "./FundraisersProductUpdateInput";

export class FundraisersProductControllerBase {
  constructor(protected readonly service: FundraisersProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FundraisersProduct })
  async createFundraisersProduct(
    @common.Body() data: FundraisersProductCreateInput
  ): Promise<FundraisersProduct> {
    return await this.service.createFundraisersProduct({
      data: {
        ...data,

        fundraisers: {
          connect: data.fundraisers,
        },

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        discount: true,
        fundraiserPrice: true,
        fundraiserPromotionUuid: true,

        fundraisers: {
          select: {
            id: true,
          },
        },

        id: true,

        product: {
          select: {
            id: true,
          },
        },

        productPrice: true,
        promotionUuid: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FundraisersProduct] })
  @ApiNestedQuery(FundraisersProductFindManyArgs)
  async fundraisersProducts(
    @common.Req() request: Request
  ): Promise<FundraisersProduct[]> {
    const args = plainToClass(FundraisersProductFindManyArgs, request.query);
    return this.service.fundraisersProducts({
      ...args,
      select: {
        createdAt: true,
        discount: true,
        fundraiserPrice: true,
        fundraiserPromotionUuid: true,

        fundraisers: {
          select: {
            id: true,
          },
        },

        id: true,

        product: {
          select: {
            id: true,
          },
        },

        productPrice: true,
        promotionUuid: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FundraisersProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fundraisersProduct(
    @common.Param() params: FundraisersProductWhereUniqueInput
  ): Promise<FundraisersProduct | null> {
    const result = await this.service.fundraisersProduct({
      where: params,
      select: {
        createdAt: true,
        discount: true,
        fundraiserPrice: true,
        fundraiserPromotionUuid: true,

        fundraisers: {
          select: {
            id: true,
          },
        },

        id: true,

        product: {
          select: {
            id: true,
          },
        },

        productPrice: true,
        promotionUuid: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FundraisersProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFundraisersProduct(
    @common.Param() params: FundraisersProductWhereUniqueInput,
    @common.Body() data: FundraisersProductUpdateInput
  ): Promise<FundraisersProduct | null> {
    try {
      return await this.service.updateFundraisersProduct({
        where: params,
        data: {
          ...data,

          fundraisers: {
            connect: data.fundraisers,
          },

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          discount: true,
          fundraiserPrice: true,
          fundraiserPromotionUuid: true,

          fundraisers: {
            select: {
              id: true,
            },
          },

          id: true,

          product: {
            select: {
              id: true,
            },
          },

          productPrice: true,
          promotionUuid: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FundraisersProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFundraisersProduct(
    @common.Param() params: FundraisersProductWhereUniqueInput
  ): Promise<FundraisersProduct | null> {
    try {
      return await this.service.deleteFundraisersProduct({
        where: params,
        select: {
          createdAt: true,
          discount: true,
          fundraiserPrice: true,
          fundraiserPromotionUuid: true,

          fundraisers: {
            select: {
              id: true,
            },
          },

          id: true,

          product: {
            select: {
              id: true,
            },
          },

          productPrice: true,
          promotionUuid: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
