/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FundraisersProduct as PrismaFundraisersProduct,
  Fundraiser as PrismaFundraiser,
  Product as PrismaProduct,
} from "@prisma/client";

export class FundraisersProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FundraisersProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.fundraisersProduct.count(args);
  }

  async fundraisersProducts(
    args: Prisma.FundraisersProductFindManyArgs
  ): Promise<PrismaFundraisersProduct[]> {
    return this.prisma.fundraisersProduct.findMany(args);
  }
  async fundraisersProduct(
    args: Prisma.FundraisersProductFindUniqueArgs
  ): Promise<PrismaFundraisersProduct | null> {
    return this.prisma.fundraisersProduct.findUnique(args);
  }
  async createFundraisersProduct(
    args: Prisma.FundraisersProductCreateArgs
  ): Promise<PrismaFundraisersProduct> {
    return this.prisma.fundraisersProduct.create(args);
  }
  async updateFundraisersProduct(
    args: Prisma.FundraisersProductUpdateArgs
  ): Promise<PrismaFundraisersProduct> {
    return this.prisma.fundraisersProduct.update(args);
  }
  async deleteFundraisersProduct(
    args: Prisma.FundraisersProductDeleteArgs
  ): Promise<PrismaFundraisersProduct> {
    return this.prisma.fundraisersProduct.delete(args);
  }

  async getFundraisers(parentId: string): Promise<PrismaFundraiser | null> {
    return this.prisma.fundraisersProduct
      .findUnique({
        where: { id: parentId },
      })
      .fundraisers();
  }

  async getProduct(parentId: string): Promise<PrismaProduct | null> {
    return this.prisma.fundraisersProduct
      .findUnique({
        where: { id: parentId },
      })
      .product();
  }
}
