/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PromotionsProductService } from "../promotionsProduct.service";
import { PromotionsProductCreateInput } from "./PromotionsProductCreateInput";
import { PromotionsProduct } from "./PromotionsProduct";
import { PromotionsProductFindManyArgs } from "./PromotionsProductFindManyArgs";
import { PromotionsProductWhereUniqueInput } from "./PromotionsProductWhereUniqueInput";
import { PromotionsProductUpdateInput } from "./PromotionsProductUpdateInput";

export class PromotionsProductControllerBase {
  constructor(protected readonly service: PromotionsProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PromotionsProduct })
  async createPromotionsProduct(
    @common.Body() data: PromotionsProductCreateInput
  ): Promise<PromotionsProduct> {
    return await this.service.createPromotionsProduct({
      data: {
        ...data,

        promotion: {
          connect: data.promotion,
        },
      },
      select: {
        createdAt: true,
        id: true,
        productUuid: true,

        promotion: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PromotionsProduct] })
  @ApiNestedQuery(PromotionsProductFindManyArgs)
  async promotionsProducts(
    @common.Req() request: Request
  ): Promise<PromotionsProduct[]> {
    const args = plainToClass(PromotionsProductFindManyArgs, request.query);
    return this.service.promotionsProducts({
      ...args,
      select: {
        createdAt: true,
        id: true,
        productUuid: true,

        promotion: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PromotionsProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async promotionsProduct(
    @common.Param() params: PromotionsProductWhereUniqueInput
  ): Promise<PromotionsProduct | null> {
    const result = await this.service.promotionsProduct({
      where: params,
      select: {
        createdAt: true,
        id: true,
        productUuid: true,

        promotion: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PromotionsProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePromotionsProduct(
    @common.Param() params: PromotionsProductWhereUniqueInput,
    @common.Body() data: PromotionsProductUpdateInput
  ): Promise<PromotionsProduct | null> {
    try {
      return await this.service.updatePromotionsProduct({
        where: params,
        data: {
          ...data,

          promotion: {
            connect: data.promotion,
          },
        },
        select: {
          createdAt: true,
          id: true,
          productUuid: true,

          promotion: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PromotionsProduct })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePromotionsProduct(
    @common.Param() params: PromotionsProductWhereUniqueInput
  ): Promise<PromotionsProduct | null> {
    try {
      return await this.service.deletePromotionsProduct({
        where: params,
        select: {
          createdAt: true,
          id: true,
          productUuid: true,

          promotion: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
