/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PromotionsProduct } from "./PromotionsProduct";
import { PromotionsProductCountArgs } from "./PromotionsProductCountArgs";
import { PromotionsProductFindManyArgs } from "./PromotionsProductFindManyArgs";
import { PromotionsProductFindUniqueArgs } from "./PromotionsProductFindUniqueArgs";
import { CreatePromotionsProductArgs } from "./CreatePromotionsProductArgs";
import { UpdatePromotionsProductArgs } from "./UpdatePromotionsProductArgs";
import { DeletePromotionsProductArgs } from "./DeletePromotionsProductArgs";
import { Promotion } from "../../promotion/base/Promotion";
import { PromotionsProductService } from "../promotionsProduct.service";
@graphql.Resolver(() => PromotionsProduct)
export class PromotionsProductResolverBase {
  constructor(protected readonly service: PromotionsProductService) {}

  async _promotionsProductsMeta(
    @graphql.Args() args: PromotionsProductCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PromotionsProduct])
  async promotionsProducts(
    @graphql.Args() args: PromotionsProductFindManyArgs
  ): Promise<PromotionsProduct[]> {
    return this.service.promotionsProducts(args);
  }

  @graphql.Query(() => PromotionsProduct, { nullable: true })
  async promotionsProduct(
    @graphql.Args() args: PromotionsProductFindUniqueArgs
  ): Promise<PromotionsProduct | null> {
    const result = await this.service.promotionsProduct(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PromotionsProduct)
  async createPromotionsProduct(
    @graphql.Args() args: CreatePromotionsProductArgs
  ): Promise<PromotionsProduct> {
    return await this.service.createPromotionsProduct({
      ...args,
      data: {
        ...args.data,

        promotion: {
          connect: args.data.promotion,
        },
      },
    });
  }

  @graphql.Mutation(() => PromotionsProduct)
  async updatePromotionsProduct(
    @graphql.Args() args: UpdatePromotionsProductArgs
  ): Promise<PromotionsProduct | null> {
    try {
      return await this.service.updatePromotionsProduct({
        ...args,
        data: {
          ...args.data,

          promotion: {
            connect: args.data.promotion,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PromotionsProduct)
  async deletePromotionsProduct(
    @graphql.Args() args: DeletePromotionsProductArgs
  ): Promise<PromotionsProduct | null> {
    try {
      return await this.service.deletePromotionsProduct(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Promotion, {
    nullable: true,
    name: "promotion",
  })
  async getPromotion(
    @graphql.Parent() parent: PromotionsProduct
  ): Promise<Promotion | null> {
    const result = await this.service.getPromotion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
