/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  PromotionsProduct as PrismaPromotionsProduct,
  Promotion as PrismaPromotion,
} from "@prisma/client";

export class PromotionsProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PromotionsProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.promotionsProduct.count(args);
  }

  async promotionsProducts(
    args: Prisma.PromotionsProductFindManyArgs
  ): Promise<PrismaPromotionsProduct[]> {
    return this.prisma.promotionsProduct.findMany(args);
  }
  async promotionsProduct(
    args: Prisma.PromotionsProductFindUniqueArgs
  ): Promise<PrismaPromotionsProduct | null> {
    return this.prisma.promotionsProduct.findUnique(args);
  }
  async createPromotionsProduct(
    args: Prisma.PromotionsProductCreateArgs
  ): Promise<PrismaPromotionsProduct> {
    return this.prisma.promotionsProduct.create(args);
  }
  async updatePromotionsProduct(
    args: Prisma.PromotionsProductUpdateArgs
  ): Promise<PrismaPromotionsProduct> {
    return this.prisma.promotionsProduct.update(args);
  }
  async deletePromotionsProduct(
    args: Prisma.PromotionsProductDeleteArgs
  ): Promise<PrismaPromotionsProduct> {
    return this.prisma.promotionsProduct.delete(args);
  }

  async getPromotion(parentId: string): Promise<PrismaPromotion | null> {
    return this.prisma.promotionsProduct
      .findUnique({
        where: { id: parentId },
      })
      .promotion();
  }
}
