/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumActivityActivityStatus } from "./EnumActivityActivityStatus";
import {
  IsEnum,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserRoleWhereUniqueInput } from "../../userRole/base/UserRoleWhereUniqueInput";
import { Type } from "class-transformer";

@InputType()
class ActivityUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumActivityActivityStatus,
  })
  @IsEnum(EnumActivityActivityStatus)
  @IsOptional()
  @Field(() => EnumActivityActivityStatus, {
    nullable: true,
  })
  activityStatus?: "INCOMPLETE" | "OVERDUE" | "EXPIRES_SOON" | "COMPLETED";

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  assigned?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  link?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  linkDrawer?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  linkName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  linkUuid?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  text?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userName?: string;

  @ApiProperty({
    required: false,
    type: () => UserRoleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserRoleWhereUniqueInput)
  @IsOptional()
  @Field(() => UserRoleWhereUniqueInput, {
    nullable: true,
  })
  userRoles?: UserRoleWhereUniqueInput | null;
}

export { ActivityUpdateInput as ActivityUpdateInput };
