/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrdersProduct } from "./OrdersProduct";
import { OrdersProductCountArgs } from "./OrdersProductCountArgs";
import { OrdersProductFindManyArgs } from "./OrdersProductFindManyArgs";
import { OrdersProductFindUniqueArgs } from "./OrdersProductFindUniqueArgs";
import { CreateOrdersProductArgs } from "./CreateOrdersProductArgs";
import { UpdateOrdersProductArgs } from "./UpdateOrdersProductArgs";
import { DeleteOrdersProductArgs } from "./DeleteOrdersProductArgs";
import { Order } from "../../order/base/Order";
import { OrdersProductService } from "../ordersProduct.service";
@graphql.Resolver(() => OrdersProduct)
export class OrdersProductResolverBase {
  constructor(protected readonly service: OrdersProductService) {}

  async _ordersProductsMeta(
    @graphql.Args() args: OrdersProductCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrdersProduct])
  async ordersProducts(
    @graphql.Args() args: OrdersProductFindManyArgs
  ): Promise<OrdersProduct[]> {
    return this.service.ordersProducts(args);
  }

  @graphql.Query(() => OrdersProduct, { nullable: true })
  async ordersProduct(
    @graphql.Args() args: OrdersProductFindUniqueArgs
  ): Promise<OrdersProduct | null> {
    const result = await this.service.ordersProduct(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrdersProduct)
  async createOrdersProduct(
    @graphql.Args() args: CreateOrdersProductArgs
  ): Promise<OrdersProduct> {
    return await this.service.createOrdersProduct({
      ...args,
      data: {
        ...args.data,

        order: {
          connect: args.data.order,
        },
      },
    });
  }

  @graphql.Mutation(() => OrdersProduct)
  async updateOrdersProduct(
    @graphql.Args() args: UpdateOrdersProductArgs
  ): Promise<OrdersProduct | null> {
    try {
      return await this.service.updateOrdersProduct({
        ...args,
        data: {
          ...args.data,

          order: {
            connect: args.data.order,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OrdersProduct)
  async deleteOrdersProduct(
    @graphql.Args() args: DeleteOrdersProductArgs
  ): Promise<OrdersProduct | null> {
    try {
      return await this.service.deleteOrdersProduct(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Order, {
    nullable: true,
    name: "order",
  })
  async getOrder(
    @graphql.Parent() parent: OrdersProduct
  ): Promise<Order | null> {
    const result = await this.service.getOrder(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
