/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  OrdersProduct as PrismaOrdersProduct,
  Order as PrismaOrder,
} from "@prisma/client";

export class OrdersProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OrdersProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.ordersProduct.count(args);
  }

  async ordersProducts(
    args: Prisma.OrdersProductFindManyArgs
  ): Promise<PrismaOrdersProduct[]> {
    return this.prisma.ordersProduct.findMany(args);
  }
  async ordersProduct(
    args: Prisma.OrdersProductFindUniqueArgs
  ): Promise<PrismaOrdersProduct | null> {
    return this.prisma.ordersProduct.findUnique(args);
  }
  async createOrdersProduct(
    args: Prisma.OrdersProductCreateArgs
  ): Promise<PrismaOrdersProduct> {
    return this.prisma.ordersProduct.create(args);
  }
  async updateOrdersProduct(
    args: Prisma.OrdersProductUpdateArgs
  ): Promise<PrismaOrdersProduct> {
    return this.prisma.ordersProduct.update(args);
  }
  async deleteOrdersProduct(
    args: Prisma.OrdersProductDeleteArgs
  ): Promise<PrismaOrdersProduct> {
    return this.prisma.ordersProduct.delete(args);
  }

  async getOrder(parentId: string): Promise<PrismaOrder | null> {
    return this.prisma.ordersProduct
      .findUnique({
        where: { id: parentId },
      })
      .order();
  }
}
