/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Inbox } from "./Inbox";
import { InboxCountArgs } from "./InboxCountArgs";
import { InboxFindManyArgs } from "./InboxFindManyArgs";
import { InboxFindUniqueArgs } from "./InboxFindUniqueArgs";
import { CreateInboxArgs } from "./CreateInboxArgs";
import { UpdateInboxArgs } from "./UpdateInboxArgs";
import { DeleteInboxArgs } from "./DeleteInboxArgs";
import { UserRole } from "../../userRole/base/UserRole";
import { InboxService } from "../inbox.service";
@graphql.Resolver(() => Inbox)
export class InboxResolverBase {
  constructor(protected readonly service: InboxService) {}

  async _inboxesMeta(
    @graphql.Args() args: InboxCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Inbox])
  async inboxes(@graphql.Args() args: InboxFindManyArgs): Promise<Inbox[]> {
    return this.service.inboxes(args);
  }

  @graphql.Query(() => Inbox, { nullable: true })
  async inbox(
    @graphql.Args() args: InboxFindUniqueArgs
  ): Promise<Inbox | null> {
    const result = await this.service.inbox(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Inbox)
  async createInbox(@graphql.Args() args: CreateInboxArgs): Promise<Inbox> {
    return await this.service.createInbox({
      ...args,
      data: {
        ...args.data,

        inboxReceiver: args.data.inboxReceiver
          ? {
              connect: args.data.inboxReceiver,
            }
          : undefined,

        inboxSender: args.data.inboxSender
          ? {
              connect: args.data.inboxSender,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Inbox)
  async updateInbox(
    @graphql.Args() args: UpdateInboxArgs
  ): Promise<Inbox | null> {
    try {
      return await this.service.updateInbox({
        ...args,
        data: {
          ...args.data,

          inboxReceiver: args.data.inboxReceiver
            ? {
                connect: args.data.inboxReceiver,
              }
            : undefined,

          inboxSender: args.data.inboxSender
            ? {
                connect: args.data.inboxSender,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Inbox)
  async deleteInbox(
    @graphql.Args() args: DeleteInboxArgs
  ): Promise<Inbox | null> {
    try {
      return await this.service.deleteInbox(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => UserRole, {
    nullable: true,
    name: "inboxReceiver",
  })
  async getInboxReceiver(
    @graphql.Parent() parent: Inbox
  ): Promise<UserRole | null> {
    const result = await this.service.getInboxReceiver(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => UserRole, {
    nullable: true,
    name: "inboxSender",
  })
  async getInboxSender(
    @graphql.Parent() parent: Inbox
  ): Promise<UserRole | null> {
    const result = await this.service.getInboxSender(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
