/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { UserRoleFindManyArgs } from "../../userRole/base/UserRoleFindManyArgs";
import { UserRole } from "../../userRole/base/UserRole";
import { UserRoleWhereUniqueInput } from "../../userRole/base/UserRoleWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        usersImages: data.usersImages
          ? {
              connect: data.usersImages,
            }
          : undefined,
      },
      select: {
        accountBsb: true,
        accountName: true,
        accountNumber: true,
        address1: true,
        address2: true,
        billerCode: true,
        billerName: true,
        billerRef: true,
        businessName: true,
        city: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        displayName: true,
        email: true,
        first: true,
        id: true,
        initials: true,
        last: true,
        phone: true,
        postcode: true,
        state: true,
        suburb: true,
        updatedAt: true,

        usersImages: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        accountBsb: true,
        accountName: true,
        accountNumber: true,
        address1: true,
        address2: true,
        billerCode: true,
        billerName: true,
        billerRef: true,
        businessName: true,
        city: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        displayName: true,
        email: true,
        first: true,
        id: true,
        initials: true,
        last: true,
        phone: true,
        postcode: true,
        state: true,
        suburb: true,
        updatedAt: true,

        usersImages: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        accountBsb: true,
        accountName: true,
        accountNumber: true,
        address1: true,
        address2: true,
        billerCode: true,
        billerName: true,
        billerRef: true,
        businessName: true,
        city: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        displayName: true,
        email: true,
        first: true,
        id: true,
        initials: true,
        last: true,
        phone: true,
        postcode: true,
        state: true,
        suburb: true,
        updatedAt: true,

        usersImages: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          usersImages: data.usersImages
            ? {
                connect: data.usersImages,
              }
            : undefined,
        },
        select: {
          accountBsb: true,
          accountName: true,
          accountNumber: true,
          address1: true,
          address2: true,
          billerCode: true,
          billerName: true,
          billerRef: true,
          businessName: true,
          city: true,
          country: true,
          createdAt: true,
          deliveryAddress: true,
          deliveryCountry: true,
          deliveryPostcode: true,
          deliveryState: true,
          deliverySuburb: true,
          displayName: true,
          email: true,
          first: true,
          id: true,
          initials: true,
          last: true,
          phone: true,
          postcode: true,
          state: true,
          suburb: true,
          updatedAt: true,

          usersImages: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          accountBsb: true,
          accountName: true,
          accountNumber: true,
          address1: true,
          address2: true,
          billerCode: true,
          billerName: true,
          billerRef: true,
          businessName: true,
          city: true,
          country: true,
          createdAt: true,
          deliveryAddress: true,
          deliveryCountry: true,
          deliveryPostcode: true,
          deliveryState: true,
          deliverySuburb: true,
          displayName: true,
          email: true,
          first: true,
          id: true,
          initials: true,
          last: true,
          phone: true,
          postcode: true,
          state: true,
          suburb: true,
          updatedAt: true,

          usersImages: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/userroles")
  @ApiNestedQuery(UserRoleFindManyArgs)
  async findUserroles(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserRole[]> {
    const query = plainToClass(UserRoleFindManyArgs, request.query);
    const results = await this.service.findUserroles(params.id, {
      ...query,
      select: {
        createdAt: true,
        emailNotification: true,
        enabled: true,
        id: true,
        roles: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userroles")
  async connectUserroles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserRoleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userroles: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userroles")
  async updateUserroles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserRoleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userroles: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userroles")
  async disconnectUserroles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserRoleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userroles: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
