/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrdersStatus } from "./OrdersStatus";
import { OrdersStatusCountArgs } from "./OrdersStatusCountArgs";
import { OrdersStatusFindManyArgs } from "./OrdersStatusFindManyArgs";
import { OrdersStatusFindUniqueArgs } from "./OrdersStatusFindUniqueArgs";
import { CreateOrdersStatusArgs } from "./CreateOrdersStatusArgs";
import { UpdateOrdersStatusArgs } from "./UpdateOrdersStatusArgs";
import { DeleteOrdersStatusArgs } from "./DeleteOrdersStatusArgs";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrdersStatusService } from "../ordersStatus.service";
@graphql.Resolver(() => OrdersStatus)
export class OrdersStatusResolverBase {
  constructor(protected readonly service: OrdersStatusService) {}

  async _ordersStatusesMeta(
    @graphql.Args() args: OrdersStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrdersStatus])
  async ordersStatuses(
    @graphql.Args() args: OrdersStatusFindManyArgs
  ): Promise<OrdersStatus[]> {
    return this.service.ordersStatuses(args);
  }

  @graphql.Query(() => OrdersStatus, { nullable: true })
  async ordersStatus(
    @graphql.Args() args: OrdersStatusFindUniqueArgs
  ): Promise<OrdersStatus | null> {
    const result = await this.service.ordersStatus(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrdersStatus)
  async createOrdersStatus(
    @graphql.Args() args: CreateOrdersStatusArgs
  ): Promise<OrdersStatus> {
    return await this.service.createOrdersStatus({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => OrdersStatus)
  async updateOrdersStatus(
    @graphql.Args() args: UpdateOrdersStatusArgs
  ): Promise<OrdersStatus | null> {
    try {
      return await this.service.updateOrdersStatus({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OrdersStatus)
  async deleteOrdersStatus(
    @graphql.Args() args: DeleteOrdersStatusArgs
  ): Promise<OrdersStatus | null> {
    try {
      return await this.service.deleteOrdersStatus(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Order], { name: "orders" })
  async findOrders(
    @graphql.Parent() parent: OrdersStatus,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
