/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  OrdersStatus as PrismaOrdersStatus,
  Order as PrismaOrder,
} from "@prisma/client";

export class OrdersStatusServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OrdersStatusCountArgs, "select">
  ): Promise<number> {
    return this.prisma.ordersStatus.count(args);
  }

  async ordersStatuses(
    args: Prisma.OrdersStatusFindManyArgs
  ): Promise<PrismaOrdersStatus[]> {
    return this.prisma.ordersStatus.findMany(args);
  }
  async ordersStatus(
    args: Prisma.OrdersStatusFindUniqueArgs
  ): Promise<PrismaOrdersStatus | null> {
    return this.prisma.ordersStatus.findUnique(args);
  }
  async createOrdersStatus(
    args: Prisma.OrdersStatusCreateArgs
  ): Promise<PrismaOrdersStatus> {
    return this.prisma.ordersStatus.create(args);
  }
  async updateOrdersStatus(
    args: Prisma.OrdersStatusUpdateArgs
  ): Promise<PrismaOrdersStatus> {
    return this.prisma.ordersStatus.update(args);
  }
  async deleteOrdersStatus(
    args: Prisma.OrdersStatusDeleteArgs
  ): Promise<PrismaOrdersStatus> {
    return this.prisma.ordersStatus.delete(args);
  }

  async findOrders(
    parentId: string,
    args: Prisma.OrderFindManyArgs
  ): Promise<PrismaOrder[]> {
    return this.prisma.ordersStatus
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .orders(args);
  }
}
