/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UsersImageService } from "../usersImage.service";
import { UsersImageCreateInput } from "./UsersImageCreateInput";
import { UsersImage } from "./UsersImage";
import { UsersImageFindManyArgs } from "./UsersImageFindManyArgs";
import { UsersImageWhereUniqueInput } from "./UsersImageWhereUniqueInput";
import { UsersImageUpdateInput } from "./UsersImageUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class UsersImageControllerBase {
  constructor(protected readonly service: UsersImageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UsersImage })
  async createUsersImage(
    @common.Body() data: UsersImageCreateInput
  ): Promise<UsersImage> {
    return await this.service.createUsersImage({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UsersImage] })
  @ApiNestedQuery(UsersImageFindManyArgs)
  async usersImages(@common.Req() request: Request): Promise<UsersImage[]> {
    const args = plainToClass(UsersImageFindManyArgs, request.query);
    return this.service.usersImages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UsersImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async usersImage(
    @common.Param() params: UsersImageWhereUniqueInput
  ): Promise<UsersImage | null> {
    const result = await this.service.usersImage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UsersImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUsersImage(
    @common.Param() params: UsersImageWhereUniqueInput,
    @common.Body() data: UsersImageUpdateInput
  ): Promise<UsersImage | null> {
    try {
      return await this.service.updateUsersImage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          path: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UsersImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUsersImage(
    @common.Param() params: UsersImageWhereUniqueInput
  ): Promise<UsersImage | null> {
    try {
      return await this.service.deleteUsersImage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          path: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: UsersImageWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        accountBsb: true,
        accountName: true,
        accountNumber: true,
        address1: true,
        address2: true,
        billerCode: true,
        billerName: true,
        billerRef: true,
        businessName: true,
        city: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        displayName: true,
        email: true,
        first: true,
        id: true,
        initials: true,
        last: true,
        phone: true,
        postcode: true,
        state: true,
        suburb: true,
        updatedAt: true,

        usersImages: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: UsersImageWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateUsersImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: UsersImageWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateUsersImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: UsersImageWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateUsersImage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
