/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UsersImage } from "./UsersImage";
import { UsersImageCountArgs } from "./UsersImageCountArgs";
import { UsersImageFindManyArgs } from "./UsersImageFindManyArgs";
import { UsersImageFindUniqueArgs } from "./UsersImageFindUniqueArgs";
import { CreateUsersImageArgs } from "./CreateUsersImageArgs";
import { UpdateUsersImageArgs } from "./UpdateUsersImageArgs";
import { DeleteUsersImageArgs } from "./DeleteUsersImageArgs";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UsersImageService } from "../usersImage.service";
@graphql.Resolver(() => UsersImage)
export class UsersImageResolverBase {
  constructor(protected readonly service: UsersImageService) {}

  async _usersImagesMeta(
    @graphql.Args() args: UsersImageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UsersImage])
  async usersImages(
    @graphql.Args() args: UsersImageFindManyArgs
  ): Promise<UsersImage[]> {
    return this.service.usersImages(args);
  }

  @graphql.Query(() => UsersImage, { nullable: true })
  async usersImage(
    @graphql.Args() args: UsersImageFindUniqueArgs
  ): Promise<UsersImage | null> {
    const result = await this.service.usersImage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UsersImage)
  async createUsersImage(
    @graphql.Args() args: CreateUsersImageArgs
  ): Promise<UsersImage> {
    return await this.service.createUsersImage({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => UsersImage)
  async updateUsersImage(
    @graphql.Args() args: UpdateUsersImageArgs
  ): Promise<UsersImage | null> {
    try {
      return await this.service.updateUsersImage({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UsersImage)
  async deleteUsersImage(
    @graphql.Args() args: DeleteUsersImageArgs
  ): Promise<UsersImage | null> {
    try {
      return await this.service.deleteUsersImage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [User], { name: "users" })
  async findUsers(
    @graphql.Parent() parent: UsersImage,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
