/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  UsersImage as PrismaUsersImage,
  User as PrismaUser,
} from "@prisma/client";

export class UsersImageServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UsersImageCountArgs, "select">
  ): Promise<number> {
    return this.prisma.usersImage.count(args);
  }

  async usersImages(
    args: Prisma.UsersImageFindManyArgs
  ): Promise<PrismaUsersImage[]> {
    return this.prisma.usersImage.findMany(args);
  }
  async usersImage(
    args: Prisma.UsersImageFindUniqueArgs
  ): Promise<PrismaUsersImage | null> {
    return this.prisma.usersImage.findUnique(args);
  }
  async createUsersImage(
    args: Prisma.UsersImageCreateArgs
  ): Promise<PrismaUsersImage> {
    return this.prisma.usersImage.create(args);
  }
  async updateUsersImage(
    args: Prisma.UsersImageUpdateArgs
  ): Promise<PrismaUsersImage> {
    return this.prisma.usersImage.update(args);
  }
  async deleteUsersImage(
    args: Prisma.UsersImageDeleteArgs
  ): Promise<PrismaUsersImage> {
    return this.prisma.usersImage.delete(args);
  }

  async findUsers(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<PrismaUser[]> {
    return this.prisma.usersImage
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .users(args);
  }
}
