import { Fundraiser } from "../fundraiser/Fundraiser";
import { OrdersProduct } from "../ordersProduct/OrdersProduct";
import { OrdersStatus } from "../ordersStatus/OrdersStatus";
import { UserRole } from "../userRole/UserRole";

export type Order = {
  additional: string | null;
  address: string | null;
  atl: boolean;
  billingAddress: string | null;
  billingCountry: string | null;
  billingPostcode: string | null;
  billingState: string | null;
  billingSuburb: string | null;
  country: string | null;
  createdAt: Date;
  deliveryAddress: string | null;
  deliveryCountry: string | null;
  deliveryPostcode: string | null;
  deliveryState: string | null;
  deliverySuburb: string | null;
  email: string | null;
  fullname: string | null;
  fundraiser?: Fundraiser | null;
  fundraiserTotal: number | null;
  id: string;
  orderId: number;
  orderTotal: number | null;
  ordersproducts?: Array<OrdersProduct>;
  ordersstatus?: OrdersStatus | null;
  phone: string | null;
  postcode: string | null;
  profit: number | null;
  shippingTotal: number | null;
  state: string | null;
  suburb: string | null;
  supplier?: UserRole | null;
  supportNotes: string | null;
  tracking: string | null;
  updatedAt: Date;
  userRoles?: UserRole | null;
};
