import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { FundraiserWhereUniqueInput } from "../fundraiser/FundraiserWhereUniqueInput";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntFilter } from "../../util/IntFilter";
import { OrdersProductListRelationFilter } from "../ordersProduct/OrdersProductListRelationFilter";
import { OrdersStatusWhereUniqueInput } from "../ordersStatus/OrdersStatusWhereUniqueInput";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";

export type OrderWhereInput = {
  additional?: StringNullableFilter;
  address?: StringNullableFilter;
  atl?: BooleanFilter;
  billingAddress?: StringNullableFilter;
  billingCountry?: StringNullableFilter;
  billingPostcode?: StringNullableFilter;
  billingState?: StringNullableFilter;
  billingSuburb?: StringNullableFilter;
  country?: StringNullableFilter;
  createdAt?: DateTimeFilter;
  deliveryAddress?: StringNullableFilter;
  deliveryCountry?: StringNullableFilter;
  deliveryPostcode?: StringNullableFilter;
  deliveryState?: StringNullableFilter;
  deliverySuburb?: StringNullableFilter;
  email?: StringNullableFilter;
  fullname?: StringNullableFilter;
  fundraiser?: FundraiserWhereUniqueInput;
  fundraiserTotal?: FloatNullableFilter;
  id?: StringFilter;
  orderId?: IntFilter;
  orderTotal?: FloatNullableFilter;
  ordersproducts?: OrdersProductListRelationFilter;
  ordersstatus?: OrdersStatusWhereUniqueInput;
  phone?: StringNullableFilter;
  postcode?: StringNullableFilter;
  profit?: FloatNullableFilter;
  shippingTotal?: FloatNullableFilter;
  state?: StringNullableFilter;
  suburb?: StringNullableFilter;
  supplier?: UserRoleWhereUniqueInput;
  supportNotes?: StringNullableFilter;
  tracking?: StringNullableFilter;
  updatedAt?: DateTimeFilter;
  userRoles?: UserRoleWhereUniqueInput;
};
