import { FundraiserWhereUniqueInput } from "../fundraiser/FundraiserWhereUniqueInput";
import { OrdersProductCreateNestedManyWithoutOrdersInput } from "./OrdersProductCreateNestedManyWithoutOrdersInput";
import { OrdersStatusWhereUniqueInput } from "../ordersStatus/OrdersStatusWhereUniqueInput";
import { UserRoleWhereUniqueInput } from "../userRole/UserRoleWhereUniqueInput";

export type OrderCreateInput = {
  additional?: string | null;
  address?: string | null;
  atl: boolean;
  billingAddress?: string | null;
  billingCountry?: string | null;
  billingPostcode?: string | null;
  billingState?: string | null;
  billingSuburb?: string | null;
  country?: string | null;
  deliveryAddress?: string | null;
  deliveryCountry?: string | null;
  deliveryPostcode?: string | null;
  deliveryState?: string | null;
  deliverySuburb?: string | null;
  email?: string | null;
  fullname?: string | null;
  fundraiser?: FundraiserWhereUniqueInput | null;
  fundraiserTotal?: number | null;
  orderId: number;
  orderTotal?: number | null;
  ordersproducts?: OrdersProductCreateNestedManyWithoutOrdersInput;
  ordersstatus?: OrdersStatusWhereUniqueInput | null;
  phone?: string | null;
  postcode?: string | null;
  profit?: number | null;
  shippingTotal?: number | null;
  state?: string | null;
  suburb?: string | null;
  supplier?: UserRoleWhereUniqueInput | null;
  supportNotes?: string | null;
  tracking?: string | null;
  userRoles?: UserRoleWhereUniqueInput | null;
};
