/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FundraiserService } from "../fundraiser.service";
import { FundraiserCreateInput } from "./FundraiserCreateInput";
import { Fundraiser } from "./Fundraiser";
import { FundraiserFindManyArgs } from "./FundraiserFindManyArgs";
import { FundraiserWhereUniqueInput } from "./FundraiserWhereUniqueInput";
import { FundraiserUpdateInput } from "./FundraiserUpdateInput";
import { FundraisersPromotionFindManyArgs } from "../../fundraisersPromotion/base/FundraisersPromotionFindManyArgs";
import { FundraisersPromotion } from "../../fundraisersPromotion/base/FundraisersPromotion";
import { FundraisersPromotionWhereUniqueInput } from "../../fundraisersPromotion/base/FundraisersPromotionWhereUniqueInput";
import { FundraisersCustomerFindManyArgs } from "../../fundraisersCustomer/base/FundraisersCustomerFindManyArgs";
import { FundraisersCustomer } from "../../fundraisersCustomer/base/FundraisersCustomer";
import { FundraisersCustomerWhereUniqueInput } from "../../fundraisersCustomer/base/FundraisersCustomerWhereUniqueInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";
import { FundraisersProductFindManyArgs } from "../../fundraisersProduct/base/FundraisersProductFindManyArgs";
import { FundraisersProduct } from "../../fundraisersProduct/base/FundraisersProduct";
import { FundraisersProductWhereUniqueInput } from "../../fundraisersProduct/base/FundraisersProductWhereUniqueInput";

export class FundraiserControllerBase {
  constructor(protected readonly service: FundraiserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Fundraiser })
  async createFundraiser(
    @common.Body() data: FundraiserCreateInput
  ): Promise<Fundraiser> {
    return await this.service.createFundraiser({
      data: {
        ...data,

        fundraisersimages: data.fundraisersimages
          ? {
              connect: data.fundraisersimages,
            }
          : undefined,

        fundraisersstatus: data.fundraisersstatus
          ? {
              connect: data.fundraisersstatus,
            }
          : undefined,

        topics: data.topics
          ? {
              connect: data.topics,
            }
          : undefined,

        userRoles: data.userRoles
          ? {
              connect: data.userRoles,
            }
          : undefined,

        userRolesFundraisersSupplierUuidToUserRoles:
          data.userRolesFundraisersSupplierUuidToUserRoles
            ? {
                connect: data.userRolesFundraisersSupplierUuidToUserRoles,
              }
            : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        endDate: true,

        fundraisersimages: {
          select: {
            id: true,
          },
        },

        fundraisersstatus: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        link: true,
        postcode: true,
        startDate: true,
        subscribed: true,
        suburb: true,
        target: true,
        title: true,
        topic: true,

        topics: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        userRolesFundraisersSupplierUuidToUserRoles: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Fundraiser] })
  @ApiNestedQuery(FundraiserFindManyArgs)
  async fundraisers(@common.Req() request: Request): Promise<Fundraiser[]> {
    const args = plainToClass(FundraiserFindManyArgs, request.query);
    return this.service.fundraisers({
      ...args,
      select: {
        createdAt: true,
        description: true,
        endDate: true,

        fundraisersimages: {
          select: {
            id: true,
          },
        },

        fundraisersstatus: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        link: true,
        postcode: true,
        startDate: true,
        subscribed: true,
        suburb: true,
        target: true,
        title: true,
        topic: true,

        topics: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        userRolesFundraisersSupplierUuidToUserRoles: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Fundraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fundraiser(
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<Fundraiser | null> {
    const result = await this.service.fundraiser({
      where: params,
      select: {
        createdAt: true,
        description: true,
        endDate: true,

        fundraisersimages: {
          select: {
            id: true,
          },
        },

        fundraisersstatus: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        link: true,
        postcode: true,
        startDate: true,
        subscribed: true,
        suburb: true,
        target: true,
        title: true,
        topic: true,

        topics: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        userRolesFundraisersSupplierUuidToUserRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Fundraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFundraiser(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() data: FundraiserUpdateInput
  ): Promise<Fundraiser | null> {
    try {
      return await this.service.updateFundraiser({
        where: params,
        data: {
          ...data,

          fundraisersimages: data.fundraisersimages
            ? {
                connect: data.fundraisersimages,
              }
            : undefined,

          fundraisersstatus: data.fundraisersstatus
            ? {
                connect: data.fundraisersstatus,
              }
            : undefined,

          topics: data.topics
            ? {
                connect: data.topics,
              }
            : undefined,

          userRoles: data.userRoles
            ? {
                connect: data.userRoles,
              }
            : undefined,

          userRolesFundraisersSupplierUuidToUserRoles:
            data.userRolesFundraisersSupplierUuidToUserRoles
              ? {
                  connect: data.userRolesFundraisersSupplierUuidToUserRoles,
                }
              : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          endDate: true,

          fundraisersimages: {
            select: {
              id: true,
            },
          },

          fundraisersstatus: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,
          link: true,
          postcode: true,
          startDate: true,
          subscribed: true,
          suburb: true,
          target: true,
          title: true,
          topic: true,

          topics: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          userRoles: {
            select: {
              id: true,
            },
          },

          userRolesFundraisersSupplierUuidToUserRoles: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Fundraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFundraiser(
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<Fundraiser | null> {
    try {
      return await this.service.deleteFundraiser({
        where: params,
        select: {
          createdAt: true,
          description: true,
          endDate: true,

          fundraisersimages: {
            select: {
              id: true,
            },
          },

          fundraisersstatus: {
            select: {
              id: true,
            },
          },

          id: true,
          image: true,
          link: true,
          postcode: true,
          startDate: true,
          subscribed: true,
          suburb: true,
          target: true,
          title: true,
          topic: true,

          topics: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          userRoles: {
            select: {
              id: true,
            },
          },

          userRolesFundraisersSupplierUuidToUserRoles: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/fundraisersPromotions")
  @ApiNestedQuery(FundraisersPromotionFindManyArgs)
  async findFundraisersPromotions(
    @common.Req() request: Request,
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<FundraisersPromotion[]> {
    const query = plainToClass(FundraisersPromotionFindManyArgs, request.query);
    const results = await this.service.findFundraisersPromotions(params.id, {
      ...query,
      select: {
        createdAt: true,

        fundraisers: {
          select: {
            id: true,
          },
        },

        id: true,

        promotions: {
          select: {
            id: true,
          },
        },

        source: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisersPromotions")
  async connectFundraisersPromotions(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersPromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersPromotions: {
        connect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisersPromotions")
  async updateFundraisersPromotions(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersPromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersPromotions: {
        set: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisersPromotions")
  async disconnectFundraisersPromotions(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersPromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersPromotions: {
        disconnect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraiserscustomers")
  @ApiNestedQuery(FundraisersCustomerFindManyArgs)
  async findFundraiserscustomers(
    @common.Req() request: Request,
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<FundraisersCustomer[]> {
    const query = plainToClass(FundraisersCustomerFindManyArgs, request.query);
    const results = await this.service.findFundraiserscustomers(params.id, {
      ...query,
      select: {
        createdAt: true,

        fundraiser: {
          select: {
            id: true,
          },
        },

        fundraisersStatus: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraiserscustomers")
  async connectFundraiserscustomers(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiserscustomers: {
        connect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraiserscustomers")
  async updateFundraiserscustomers(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiserscustomers: {
        set: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraiserscustomers")
  async disconnectFundraiserscustomers(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiserscustomers: {
        disconnect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraisersorders")
  @ApiNestedQuery(OrderFindManyArgs)
  async findFundraisersorders(
    @common.Req() request: Request,
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findFundraisersorders(params.id, {
      ...query,
      select: {
        additional: true,
        address: true,
        atl: true,
        billingAddress: true,
        billingCountry: true,
        billingPostcode: true,
        billingState: true,
        billingSuburb: true,
        country: true,
        createdAt: true,
        deliveryAddress: true,
        deliveryCountry: true,
        deliveryPostcode: true,
        deliveryState: true,
        deliverySuburb: true,
        email: true,
        fullname: true,

        fundraiser: {
          select: {
            id: true,
          },
        },

        fundraiserTotal: true,
        id: true,
        orderId: true,
        orderTotal: true,

        ordersstatus: {
          select: {
            id: true,
          },
        },

        phone: true,
        postcode: true,
        profit: true,
        shippingTotal: true,
        state: true,
        suburb: true,

        supplier: {
          select: {
            id: true,
          },
        },

        supportNotes: true,
        tracking: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisersorders")
  async connectFundraisersorders(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersorders: {
        connect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisersorders")
  async updateFundraisersorders(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersorders: {
        set: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisersorders")
  async disconnectFundraisersorders(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersorders: {
        disconnect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraisersproducts")
  @ApiNestedQuery(FundraisersProductFindManyArgs)
  async findFundraisersproducts(
    @common.Req() request: Request,
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<FundraisersProduct[]> {
    const query = plainToClass(FundraisersProductFindManyArgs, request.query);
    const results = await this.service.findFundraisersproducts(params.id, {
      ...query,
      select: {
        createdAt: true,
        discount: true,
        fundraiserPrice: true,
        fundraiserPromotionUuid: true,

        fundraisers: {
          select: {
            id: true,
          },
        },

        id: true,

        product: {
          select: {
            id: true,
          },
        },

        productPrice: true,
        promotionUuid: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisersproducts")
  async connectFundraisersproducts(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersproducts: {
        connect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisersproducts")
  async updateFundraisersproducts(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersproducts: {
        set: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisersproducts")
  async disconnectFundraisersproducts(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: FundraisersProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisersproducts: {
        disconnect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
