/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsDate,
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsBoolean,
  IsInt,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { FundraisersPromotion } from "../../fundraisersPromotion/base/FundraisersPromotion";
import { FundraisersCustomer } from "../../fundraisersCustomer/base/FundraisersCustomer";
import { FundraisersImage } from "../../fundraisersImage/base/FundraisersImage";
import { Order } from "../../order/base/Order";
import { FundraisersProduct } from "../../fundraisersProduct/base/FundraisersProduct";
import { FundraisersStatus } from "../../fundraisersStatus/base/FundraisersStatus";
import { Topic } from "../../topic/base/Topic";
import { UserRole } from "../../userRole/base/UserRole";

@ObjectType()
class Fundraiser {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endDate!: Date;

  @ApiProperty({
    required: false,
    type: () => [FundraisersPromotion],
  })
  @ValidateNested()
  @Type(() => FundraisersPromotion)
  @IsOptional()
  fundraisersPromotions?: Array<FundraisersPromotion>;

  @ApiProperty({
    required: false,
    type: () => [FundraisersCustomer],
  })
  @ValidateNested()
  @Type(() => FundraisersCustomer)
  @IsOptional()
  fundraiserscustomers?: Array<FundraisersCustomer>;

  @ApiProperty({
    required: false,
    type: () => FundraisersImage,
  })
  @ValidateNested()
  @Type(() => FundraisersImage)
  @IsOptional()
  fundraisersimages?: FundraisersImage | null;

  @ApiProperty({
    required: false,
    type: () => [Order],
  })
  @ValidateNested()
  @Type(() => Order)
  @IsOptional()
  fundraisersorders?: Array<Order>;

  @ApiProperty({
    required: false,
    type: () => [FundraisersProduct],
  })
  @ValidateNested()
  @Type(() => FundraisersProduct)
  @IsOptional()
  fundraisersproducts?: Array<FundraisersProduct>;

  @ApiProperty({
    required: false,
    type: () => FundraisersStatus,
  })
  @ValidateNested()
  @Type(() => FundraisersStatus)
  @IsOptional()
  fundraisersstatus?: FundraisersStatus | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  image!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  link!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postcode!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startDate!: Date;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  subscribed!: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  suburb!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  target!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  topic!: string | null;

  @ApiProperty({
    required: false,
    type: () => Topic,
  })
  @ValidateNested()
  @Type(() => Topic)
  @IsOptional()
  topics?: Topic | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => UserRole,
  })
  @ValidateNested()
  @Type(() => UserRole)
  @IsOptional()
  userRoles?: UserRole | null;

  @ApiProperty({
    required: false,
    type: () => UserRole,
  })
  @ValidateNested()
  @Type(() => UserRole)
  @IsOptional()
  userRolesFundraisersSupplierUuidToUserRoles?: UserRole | null;
}

export { Fundraiser as Fundraiser };
