/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PromotionsImageService } from "../promotionsImage.service";
import { PromotionsImageCreateInput } from "./PromotionsImageCreateInput";
import { PromotionsImage } from "./PromotionsImage";
import { PromotionsImageFindManyArgs } from "./PromotionsImageFindManyArgs";
import { PromotionsImageWhereUniqueInput } from "./PromotionsImageWhereUniqueInput";
import { PromotionsImageUpdateInput } from "./PromotionsImageUpdateInput";
import { PromotionFindManyArgs } from "../../promotion/base/PromotionFindManyArgs";
import { Promotion } from "../../promotion/base/Promotion";
import { PromotionWhereUniqueInput } from "../../promotion/base/PromotionWhereUniqueInput";

export class PromotionsImageControllerBase {
  constructor(protected readonly service: PromotionsImageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PromotionsImage })
  async createPromotionsImage(
    @common.Body() data: PromotionsImageCreateInput
  ): Promise<PromotionsImage> {
    return await this.service.createPromotionsImage({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [PromotionsImage] })
  @ApiNestedQuery(PromotionsImageFindManyArgs)
  async promotionsImages(
    @common.Req() request: Request
  ): Promise<PromotionsImage[]> {
    const args = plainToClass(PromotionsImageFindManyArgs, request.query);
    return this.service.promotionsImages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PromotionsImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async promotionsImage(
    @common.Param() params: PromotionsImageWhereUniqueInput
  ): Promise<PromotionsImage | null> {
    const result = await this.service.promotionsImage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        path: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PromotionsImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePromotionsImage(
    @common.Param() params: PromotionsImageWhereUniqueInput,
    @common.Body() data: PromotionsImageUpdateInput
  ): Promise<PromotionsImage | null> {
    try {
      return await this.service.updatePromotionsImage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          path: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PromotionsImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePromotionsImage(
    @common.Param() params: PromotionsImageWhereUniqueInput
  ): Promise<PromotionsImage | null> {
    try {
      return await this.service.deletePromotionsImage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          path: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/promotions")
  @ApiNestedQuery(PromotionFindManyArgs)
  async findPromotions(
    @common.Req() request: Request,
    @common.Param() params: PromotionsImageWhereUniqueInput
  ): Promise<Promotion[]> {
    const query = plainToClass(PromotionFindManyArgs, request.query);
    const results = await this.service.findPromotions(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        discount: true,
        endDate: true,
        excerpt: true,
        id: true,

        image: {
          select: {
            id: true,
          },
        },

        max: true,
        min: true,
        name: true,
        promotionMethod: true,
        promotionStatus: true,
        promotionType: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/promotions")
  async connectPromotions(
    @common.Param() params: PromotionsImageWhereUniqueInput,
    @common.Body() body: PromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promotions: {
        connect: body,
      },
    };
    await this.service.updatePromotionsImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/promotions")
  async updatePromotions(
    @common.Param() params: PromotionsImageWhereUniqueInput,
    @common.Body() body: PromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promotions: {
        set: body,
      },
    };
    await this.service.updatePromotionsImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/promotions")
  async disconnectPromotions(
    @common.Param() params: PromotionsImageWhereUniqueInput,
    @common.Body() body: PromotionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      promotions: {
        disconnect: body,
      },
    };
    await this.service.updatePromotionsImage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
