/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  PromotionsImage as PrismaPromotionsImage,
  Promotion as PrismaPromotion,
} from "@prisma/client";

export class PromotionsImageServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PromotionsImageCountArgs, "select">
  ): Promise<number> {
    return this.prisma.promotionsImage.count(args);
  }

  async promotionsImages(
    args: Prisma.PromotionsImageFindManyArgs
  ): Promise<PrismaPromotionsImage[]> {
    return this.prisma.promotionsImage.findMany(args);
  }
  async promotionsImage(
    args: Prisma.PromotionsImageFindUniqueArgs
  ): Promise<PrismaPromotionsImage | null> {
    return this.prisma.promotionsImage.findUnique(args);
  }
  async createPromotionsImage(
    args: Prisma.PromotionsImageCreateArgs
  ): Promise<PrismaPromotionsImage> {
    return this.prisma.promotionsImage.create(args);
  }
  async updatePromotionsImage(
    args: Prisma.PromotionsImageUpdateArgs
  ): Promise<PrismaPromotionsImage> {
    return this.prisma.promotionsImage.update(args);
  }
  async deletePromotionsImage(
    args: Prisma.PromotionsImageDeleteArgs
  ): Promise<PrismaPromotionsImage> {
    return this.prisma.promotionsImage.delete(args);
  }

  async findPromotions(
    parentId: string,
    args: Prisma.PromotionFindManyArgs
  ): Promise<PrismaPromotion[]> {
    return this.prisma.promotionsImage
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .promotions(args);
  }
}
