/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FundraisersImageService } from "../fundraisersImage.service";
import { FundraisersImageCreateInput } from "./FundraisersImageCreateInput";
import { FundraisersImage } from "./FundraisersImage";
import { FundraisersImageFindManyArgs } from "./FundraisersImageFindManyArgs";
import { FundraisersImageWhereUniqueInput } from "./FundraisersImageWhereUniqueInput";
import { FundraisersImageUpdateInput } from "./FundraisersImageUpdateInput";
import { FundraiserFindManyArgs } from "../../fundraiser/base/FundraiserFindManyArgs";
import { Fundraiser } from "../../fundraiser/base/Fundraiser";
import { FundraiserWhereUniqueInput } from "../../fundraiser/base/FundraiserWhereUniqueInput";

export class FundraisersImageControllerBase {
  constructor(protected readonly service: FundraisersImageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FundraisersImage })
  async createFundraisersImage(
    @common.Body() data: FundraisersImageCreateInput
  ): Promise<FundraisersImage> {
    return await this.service.createFundraisersImage({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        path: true,
        theme: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FundraisersImage] })
  @ApiNestedQuery(FundraisersImageFindManyArgs)
  async fundraisersImages(
    @common.Req() request: Request
  ): Promise<FundraisersImage[]> {
    const args = plainToClass(FundraisersImageFindManyArgs, request.query);
    return this.service.fundraisersImages({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        path: true,
        theme: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FundraisersImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fundraisersImage(
    @common.Param() params: FundraisersImageWhereUniqueInput
  ): Promise<FundraisersImage | null> {
    const result = await this.service.fundraisersImage({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        path: true,
        theme: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FundraisersImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFundraisersImage(
    @common.Param() params: FundraisersImageWhereUniqueInput,
    @common.Body() data: FundraisersImageUpdateInput
  ): Promise<FundraisersImage | null> {
    try {
      return await this.service.updateFundraisersImage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          path: true,
          theme: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FundraisersImage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFundraisersImage(
    @common.Param() params: FundraisersImageWhereUniqueInput
  ): Promise<FundraisersImage | null> {
    try {
      return await this.service.deleteFundraisersImage({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          path: true,
          theme: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/fundraisers")
  @ApiNestedQuery(FundraiserFindManyArgs)
  async findFundraisers(
    @common.Req() request: Request,
    @common.Param() params: FundraisersImageWhereUniqueInput
  ): Promise<Fundraiser[]> {
    const query = plainToClass(FundraiserFindManyArgs, request.query);
    const results = await this.service.findFundraisers(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        endDate: true,

        fundraisersimages: {
          select: {
            id: true,
          },
        },

        fundraisersstatus: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        link: true,
        postcode: true,
        startDate: true,
        subscribed: true,
        suburb: true,
        target: true,
        title: true,
        topic: true,

        topics: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        userRolesFundraisersSupplierUuidToUserRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisers")
  async connectFundraisers(
    @common.Param() params: FundraisersImageWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisers: {
        connect: body,
      },
    };
    await this.service.updateFundraisersImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisers")
  async updateFundraisers(
    @common.Param() params: FundraisersImageWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisers: {
        set: body,
      },
    };
    await this.service.updateFundraisersImage({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisers")
  async disconnectFundraisers(
    @common.Param() params: FundraisersImageWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisers: {
        disconnect: body,
      },
    };
    await this.service.updateFundraisersImage({
      where: params,
      data,
      select: { id: true },
    });
  }
}
