/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FundraisersStatusService } from "../fundraisersStatus.service";
import { FundraisersStatusCreateInput } from "./FundraisersStatusCreateInput";
import { FundraisersStatus } from "./FundraisersStatus";
import { FundraisersStatusFindManyArgs } from "./FundraisersStatusFindManyArgs";
import { FundraisersStatusWhereUniqueInput } from "./FundraisersStatusWhereUniqueInput";
import { FundraisersStatusUpdateInput } from "./FundraisersStatusUpdateInput";
import { FundraiserFindManyArgs } from "../../fundraiser/base/FundraiserFindManyArgs";
import { Fundraiser } from "../../fundraiser/base/Fundraiser";
import { FundraiserWhereUniqueInput } from "../../fundraiser/base/FundraiserWhereUniqueInput";
import { FundraisersCustomerFindManyArgs } from "../../fundraisersCustomer/base/FundraisersCustomerFindManyArgs";
import { FundraisersCustomer } from "../../fundraisersCustomer/base/FundraisersCustomer";
import { FundraisersCustomerWhereUniqueInput } from "../../fundraisersCustomer/base/FundraisersCustomerWhereUniqueInput";

export class FundraisersStatusControllerBase {
  constructor(protected readonly service: FundraisersStatusService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FundraisersStatus })
  async createFundraisersStatus(
    @common.Body() data: FundraisersStatusCreateInput
  ): Promise<FundraisersStatus> {
    return await this.service.createFundraisersStatus({
      data: data,
      select: {
        id: true,
        name: true,
        sequence: true,
        status: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FundraisersStatus] })
  @ApiNestedQuery(FundraisersStatusFindManyArgs)
  async fundraisersStatuses(
    @common.Req() request: Request
  ): Promise<FundraisersStatus[]> {
    const args = plainToClass(FundraisersStatusFindManyArgs, request.query);
    return this.service.fundraisersStatuses({
      ...args,
      select: {
        id: true,
        name: true,
        sequence: true,
        status: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FundraisersStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async fundraisersStatus(
    @common.Param() params: FundraisersStatusWhereUniqueInput
  ): Promise<FundraisersStatus | null> {
    const result = await this.service.fundraisersStatus({
      where: params,
      select: {
        id: true,
        name: true,
        sequence: true,
        status: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FundraisersStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFundraisersStatus(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() data: FundraisersStatusUpdateInput
  ): Promise<FundraisersStatus | null> {
    try {
      return await this.service.updateFundraisersStatus({
        where: params,
        data: data,
        select: {
          id: true,
          name: true,
          sequence: true,
          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FundraisersStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFundraisersStatus(
    @common.Param() params: FundraisersStatusWhereUniqueInput
  ): Promise<FundraisersStatus | null> {
    try {
      return await this.service.deleteFundraisersStatus({
        where: params,
        select: {
          id: true,
          name: true,
          sequence: true,
          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/fundraiser")
  @ApiNestedQuery(FundraiserFindManyArgs)
  async findFundraiser(
    @common.Req() request: Request,
    @common.Param() params: FundraisersStatusWhereUniqueInput
  ): Promise<Fundraiser[]> {
    const query = plainToClass(FundraiserFindManyArgs, request.query);
    const results = await this.service.findFundraiser(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        endDate: true,

        fundraisersimages: {
          select: {
            id: true,
          },
        },

        fundraisersstatus: {
          select: {
            id: true,
          },
        },

        id: true,
        image: true,
        link: true,
        postcode: true,
        startDate: true,
        subscribed: true,
        suburb: true,
        target: true,
        title: true,
        topic: true,

        topics: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },

        userRolesFundraisersSupplierUuidToUserRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraiser")
  async connectFundraiser(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiser: {
        connect: body,
      },
    };
    await this.service.updateFundraisersStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraiser")
  async updateFundraiser(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiser: {
        set: body,
      },
    };
    await this.service.updateFundraisersStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraiser")
  async disconnectFundraiser(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() body: FundraiserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraiser: {
        disconnect: body,
      },
    };
    await this.service.updateFundraisersStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/fundraisercustomers")
  @ApiNestedQuery(FundraisersCustomerFindManyArgs)
  async findFundraisercustomers(
    @common.Req() request: Request,
    @common.Param() params: FundraisersStatusWhereUniqueInput
  ): Promise<FundraisersCustomer[]> {
    const query = plainToClass(FundraisersCustomerFindManyArgs, request.query);
    const results = await this.service.findFundraisercustomers(params.id, {
      ...query,
      select: {
        createdAt: true,

        fundraiser: {
          select: {
            id: true,
          },
        },

        fundraisersStatus: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/fundraisercustomers")
  async connectFundraisercustomers(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisercustomers: {
        connect: body,
      },
    };
    await this.service.updateFundraisersStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/fundraisercustomers")
  async updateFundraisercustomers(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisercustomers: {
        set: body,
      },
    };
    await this.service.updateFundraisersStatus({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/fundraisercustomers")
  async disconnectFundraisercustomers(
    @common.Param() params: FundraisersStatusWhereUniqueInput,
    @common.Body() body: FundraisersCustomerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fundraisercustomers: {
        disconnect: body,
      },
    };
    await this.service.updateFundraisersStatus({
      where: params,
      data,
      select: { id: true },
    });
  }
}
