/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { FundraiserWhereUniqueInput } from "../../fundraiser/base/FundraiserWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { PromotionWhereUniqueInput } from "../../promotion/base/PromotionWhereUniqueInput";
import { EnumFundraisersPromotionSource } from "./EnumFundraisersPromotionSource";
import { EnumFundraisersPromotionStatus } from "./EnumFundraisersPromotionStatus";

@InputType()
class FundraisersPromotionWhereInput {
  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  createdAt?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => FundraiserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FundraiserWhereUniqueInput)
  @IsOptional()
  @Field(() => FundraiserWhereUniqueInput, {
    nullable: true,
  })
  fundraisers?: FundraiserWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PromotionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PromotionWhereUniqueInput)
  @IsOptional()
  @Field(() => PromotionWhereUniqueInput, {
    nullable: true,
  })
  promotions?: PromotionWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumFundraisersPromotionSource,
  })
  @IsEnum(EnumFundraisersPromotionSource)
  @IsOptional()
  @Field(() => EnumFundraisersPromotionSource, {
    nullable: true,
  })
  source?: "PARTNER" | "FUNDRAISER";

  @ApiProperty({
    required: false,
    enum: EnumFundraisersPromotionStatus,
  })
  @IsEnum(EnumFundraisersPromotionStatus)
  @IsOptional()
  @Field(() => EnumFundraisersPromotionStatus, {
    nullable: true,
  })
  status?: "ACTIVE" | "INACTIVE" | "EXPIRES_SOON" | "EXPIRED";

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  updatedAt?: DateTimeFilter;
}

export { FundraisersPromotionWhereInput as FundraisersPromotionWhereInput };
