/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Order } from "./Order";
import { OrderCountArgs } from "./OrderCountArgs";
import { OrderFindManyArgs } from "./OrderFindManyArgs";
import { OrderFindUniqueArgs } from "./OrderFindUniqueArgs";
import { CreateOrderArgs } from "./CreateOrderArgs";
import { UpdateOrderArgs } from "./UpdateOrderArgs";
import { DeleteOrderArgs } from "./DeleteOrderArgs";
import { OrdersProductFindManyArgs } from "../../ordersProduct/base/OrdersProductFindManyArgs";
import { OrdersProduct } from "../../ordersProduct/base/OrdersProduct";
import { Fundraiser } from "../../fundraiser/base/Fundraiser";
import { OrdersStatus } from "../../ordersStatus/base/OrdersStatus";
import { UserRole } from "../../userRole/base/UserRole";
import { OrderService } from "../order.service";
@graphql.Resolver(() => Order)
export class OrderResolverBase {
  constructor(protected readonly service: OrderService) {}

  async _ordersMeta(
    @graphql.Args() args: OrderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Order])
  async orders(@graphql.Args() args: OrderFindManyArgs): Promise<Order[]> {
    return this.service.orders(args);
  }

  @graphql.Query(() => Order, { nullable: true })
  async order(
    @graphql.Args() args: OrderFindUniqueArgs
  ): Promise<Order | null> {
    const result = await this.service.order(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Order)
  async createOrder(@graphql.Args() args: CreateOrderArgs): Promise<Order> {
    return await this.service.createOrder({
      ...args,
      data: {
        ...args.data,

        fundraiser: args.data.fundraiser
          ? {
              connect: args.data.fundraiser,
            }
          : undefined,

        ordersstatus: args.data.ordersstatus
          ? {
              connect: args.data.ordersstatus,
            }
          : undefined,

        supplier: args.data.supplier
          ? {
              connect: args.data.supplier,
            }
          : undefined,

        userRoles: args.data.userRoles
          ? {
              connect: args.data.userRoles,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Order)
  async updateOrder(
    @graphql.Args() args: UpdateOrderArgs
  ): Promise<Order | null> {
    try {
      return await this.service.updateOrder({
        ...args,
        data: {
          ...args.data,

          fundraiser: args.data.fundraiser
            ? {
                connect: args.data.fundraiser,
              }
            : undefined,

          ordersstatus: args.data.ordersstatus
            ? {
                connect: args.data.ordersstatus,
              }
            : undefined,

          supplier: args.data.supplier
            ? {
                connect: args.data.supplier,
              }
            : undefined,

          userRoles: args.data.userRoles
            ? {
                connect: args.data.userRoles,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Order)
  async deleteOrder(
    @graphql.Args() args: DeleteOrderArgs
  ): Promise<Order | null> {
    try {
      return await this.service.deleteOrder(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [OrdersProduct], { name: "ordersproducts" })
  async findOrdersproducts(
    @graphql.Parent() parent: Order,
    @graphql.Args() args: OrdersProductFindManyArgs
  ): Promise<OrdersProduct[]> {
    const results = await this.service.findOrdersproducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Fundraiser, {
    nullable: true,
    name: "fundraiser",
  })
  async getFundraiser(
    @graphql.Parent() parent: Order
  ): Promise<Fundraiser | null> {
    const result = await this.service.getFundraiser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => OrdersStatus, {
    nullable: true,
    name: "ordersstatus",
  })
  async getOrdersstatus(
    @graphql.Parent() parent: Order
  ): Promise<OrdersStatus | null> {
    const result = await this.service.getOrdersstatus(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => UserRole, {
    nullable: true,
    name: "supplier",
  })
  async getSupplier(@graphql.Parent() parent: Order): Promise<UserRole | null> {
    const result = await this.service.getSupplier(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => UserRole, {
    nullable: true,
    name: "userRoles",
  })
  async getUserRoles(
    @graphql.Parent() parent: Order
  ): Promise<UserRole | null> {
    const result = await this.service.getUserRoles(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
