/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Postcode as PrismaPostcode,
  UserRole as PrismaUserRole,
} from "@prisma/client";

export class PostcodeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PostcodeCountArgs, "select">): Promise<number> {
    return this.prisma.postcode.count(args);
  }

  async postcodes(
    args: Prisma.PostcodeFindManyArgs
  ): Promise<PrismaPostcode[]> {
    return this.prisma.postcode.findMany(args);
  }
  async postcode(
    args: Prisma.PostcodeFindUniqueArgs
  ): Promise<PrismaPostcode | null> {
    return this.prisma.postcode.findUnique(args);
  }
  async createPostcode(
    args: Prisma.PostcodeCreateArgs
  ): Promise<PrismaPostcode> {
    return this.prisma.postcode.create(args);
  }
  async updatePostcode(
    args: Prisma.PostcodeUpdateArgs
  ): Promise<PrismaPostcode> {
    return this.prisma.postcode.update(args);
  }
  async deletePostcode(
    args: Prisma.PostcodeDeleteArgs
  ): Promise<PrismaPostcode> {
    return this.prisma.postcode.delete(args);
  }

  async getUserRoles(parentId: string): Promise<PrismaUserRole | null> {
    return this.prisma.postcode
      .findUnique({
        where: { id: parentId },
      })
      .userRoles();
  }
}
