/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PostcodeService } from "../postcode.service";
import { PostcodeCreateInput } from "./PostcodeCreateInput";
import { Postcode } from "./Postcode";
import { PostcodeFindManyArgs } from "./PostcodeFindManyArgs";
import { PostcodeWhereUniqueInput } from "./PostcodeWhereUniqueInput";
import { PostcodeUpdateInput } from "./PostcodeUpdateInput";

export class PostcodeControllerBase {
  constructor(protected readonly service: PostcodeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Postcode })
  async createPostcode(
    @common.Body() data: PostcodeCreateInput
  ): Promise<Postcode> {
    return await this.service.createPostcode({
      data: {
        ...data,

        userRoles: data.userRoles
          ? {
              connect: data.userRoles,
            }
          : undefined,
      },
      select: {
        code: true,
        createdAt: true,
        id: true,
        metro: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Postcode] })
  @ApiNestedQuery(PostcodeFindManyArgs)
  async postcodes(@common.Req() request: Request): Promise<Postcode[]> {
    const args = plainToClass(PostcodeFindManyArgs, request.query);
    return this.service.postcodes({
      ...args,
      select: {
        code: true,
        createdAt: true,
        id: true,
        metro: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Postcode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async postcode(
    @common.Param() params: PostcodeWhereUniqueInput
  ): Promise<Postcode | null> {
    const result = await this.service.postcode({
      where: params,
      select: {
        code: true,
        createdAt: true,
        id: true,
        metro: true,
        updatedAt: true,

        userRoles: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Postcode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePostcode(
    @common.Param() params: PostcodeWhereUniqueInput,
    @common.Body() data: PostcodeUpdateInput
  ): Promise<Postcode | null> {
    try {
      return await this.service.updatePostcode({
        where: params,
        data: {
          ...data,

          userRoles: data.userRoles
            ? {
                connect: data.userRoles,
              }
            : undefined,
        },
        select: {
          code: true,
          createdAt: true,
          id: true,
          metro: true,
          updatedAt: true,

          userRoles: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Postcode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePostcode(
    @common.Param() params: PostcodeWhereUniqueInput
  ): Promise<Postcode | null> {
    try {
      return await this.service.deletePostcode({
        where: params,
        select: {
          code: true,
          createdAt: true,
          id: true,
          metro: true,
          updatedAt: true,

          userRoles: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
