/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Postcode } from "./Postcode";
import { PostcodeCountArgs } from "./PostcodeCountArgs";
import { PostcodeFindManyArgs } from "./PostcodeFindManyArgs";
import { PostcodeFindUniqueArgs } from "./PostcodeFindUniqueArgs";
import { CreatePostcodeArgs } from "./CreatePostcodeArgs";
import { UpdatePostcodeArgs } from "./UpdatePostcodeArgs";
import { DeletePostcodeArgs } from "./DeletePostcodeArgs";
import { UserRole } from "../../userRole/base/UserRole";
import { PostcodeService } from "../postcode.service";
@graphql.Resolver(() => Postcode)
export class PostcodeResolverBase {
  constructor(protected readonly service: PostcodeService) {}

  async _postcodesMeta(
    @graphql.Args() args: PostcodeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Postcode])
  async postcodes(
    @graphql.Args() args: PostcodeFindManyArgs
  ): Promise<Postcode[]> {
    return this.service.postcodes(args);
  }

  @graphql.Query(() => Postcode, { nullable: true })
  async postcode(
    @graphql.Args() args: PostcodeFindUniqueArgs
  ): Promise<Postcode | null> {
    const result = await this.service.postcode(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Postcode)
  async createPostcode(
    @graphql.Args() args: CreatePostcodeArgs
  ): Promise<Postcode> {
    return await this.service.createPostcode({
      ...args,
      data: {
        ...args.data,

        userRoles: args.data.userRoles
          ? {
              connect: args.data.userRoles,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Postcode)
  async updatePostcode(
    @graphql.Args() args: UpdatePostcodeArgs
  ): Promise<Postcode | null> {
    try {
      return await this.service.updatePostcode({
        ...args,
        data: {
          ...args.data,

          userRoles: args.data.userRoles
            ? {
                connect: args.data.userRoles,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Postcode)
  async deletePostcode(
    @graphql.Args() args: DeletePostcodeArgs
  ): Promise<Postcode | null> {
    try {
      return await this.service.deletePostcode(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => UserRole, {
    nullable: true,
    name: "userRoles",
  })
  async getUserRoles(
    @graphql.Parent() parent: Postcode
  ): Promise<UserRole | null> {
    const result = await this.service.getUserRoles(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
